!2D FILE GENERATION FOR PARAVIEW (PEDRO GODOI 2025)
SUBROUTINE GNUPLOT_CUBE(NX,NY,NZ,FRAME,GTYPE,CENTERS,RHO,PRE,VX,VY,VZ,BOUNDS)

USE ISO_C_BINDING

IMPLICIT NONE
!INPUT
REAL(KIND=C_DOUBLE),DIMENSION(NX,NY,NZ),INTENT(IN)  :: RHO,PRE,VX,VY,VZ
REAL(KIND=C_DOUBLE),DIMENSION(NX,NY,NZ,3),INTENT(IN):: CENTERS
INTEGER(KIND=C_INT),INTENT(IN)                      :: NX,NY,NZ,FRAME,GTYPE
INTEGER(KIND=C_INT),DIMENSION(NX,NY,NZ),INTENT(IN)  :: BOUNDS
!LOCAL
INTEGER(KIND=C_INT)	         				:: I,J,K
CHARACTER(KIND=C_CHAR,LEN=8)				:: FRAME_STR

!!!WRITE FRAME AS STRING
WRITE(FRAME_STR,'(I0.8)') FRAME

SELECT CASE(GTYPE)
CASE(0) !2D SLICE

OPEN(77,FILE='OUTPUT/ANIMA/EE2D_'//FRAME_STR//'.CSV',STATUS='NEW')
WRITE(77,'(A33)') 'X,Z,DENSITY,PRESSURE,VX,VZ,BOUNDS'

DO K=2,NZ-1
DO I=2,NX-1
	WRITE(77,'(E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,I02)')&
	CENTERS(I,NY/2,K,1),',',CENTERS(I,NY/2,K,3),',',&
	RHO(I,NY/2,K),',',PRE(I,NY/2,K),',',VX(I,NY/2,K),',',VZ(I,NY/2,K),&
	',',BOUNDS(I,NY/2,K)
END DO
!WRITE(77,*)
END DO
CLOSE(77)


CASE(1) !FULL 3D

OPEN(77,FILE='OUTPUT/ANIMA/EE3D_'//FRAME_STR//'.CSV',STATUS='NEW')
WRITE(77,'(A38)') 'X,Y,Z,DENSITY,PRESSURE,VX,VY,VZ,BOUNDS'

OPEN(77,FILE='OUTPUT/ANIMA/EE3D_'//FRAME_STR//'.CSV',STATUS='OLD',POSITION='APPEND')
DO K=2,NZ-1
DO J=2,NY-1
DO I=2,NX-1
	WRITE(77,'(E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,I02)')&
	CENTERS(I,J,K,1),',',CENTERS(I,J,K,2),',',CENTERS(I,J,K,3),',',&
	RHO(I,J,K),',',PRE(I,J,K),',',VX(I,J,K),',',VY(I,J,K),',',VZ(I,J,K),',',BOUNDS(I,J,K)
END DO
END DO
END DO
CLOSE(77)

CASE(2) !2D SLICE DEBUG

OPEN(77,FILE='OUTPUT/ANIMA/EE2D_'//FRAME_STR//'.CSV',STATUS='NEW')
WRITE(77,'(A33)') 'X,Z,DENSITY,PRESSURE,VX,VZ,BOUNDS'

DO K=1,NZ
DO I=1,NX
	WRITE(77,'(E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,E21.8E4,A1,I02)')&
	CENTERS(I,NY/2,K,1),',',CENTERS(I,NY/2,K,3),',',&
	RHO(I,NY/2,K),',',PRE(I,NY/2,K),',',VX(I,NY/2,K),',',VZ(I,NY/2,K),&
	',',BOUNDS(I,NY/2,K)
END DO
!WRITE(77,*)
END DO
CLOSE(77)

END SELECT

END SUBROUTINE