!INITAL CONDITION FOR CUBE MESH(PEDRO GODOI 2025)
SUBROUTINE COND_INITIAL_CUBE(NX,NY,NZ,CENTERS,CI_TYPE,RHO,VX,VY,VZ,ENE,PRE,BOUNDS)

USE CUDAFOR
USE ISO_C_BINDING
USE COND_INITIAL_CUBE_CUDA

IMPLICIT NONE
!INPUT
REAL(KIND=C_DOUBLE),DIMENSION(NX,NY,NZ,3),INTENT(IN)     :: CENTERS
INTEGER(KIND=C_INT),INTENT(IN)                           :: NX,NY,NZ,CI_TYPE
INTEGER(KIND=C_INT),DIMENSION(NX,NY,NZ),INTENT(IN)		 :: BOUNDS
!OUTPUT
REAL(KIND=C_DOUBLE),DIMENSION(NX,NY,NZ),INTENT(OUT)      :: RHO,VX,VY,VZ,ENE,PRE

!LOCAL VARIABLES
REAL(KIND=C_DOUBLE)          :: GAMA
INTEGER(KIND=C_INT)          :: I,J,K
TYPE(DIM3)				     :: GRID, TBLOCK !CUDA

!DEVICE VARIABLES
INTEGER(KIND=C_INT),ALLOCATABLE,DIMENSION(:,:,:),DEVICE  :: BOUNDS_D
REAL(KIND=C_DOUBLE),ALLOCATABLE,DIMENSION(:,:,:),DEVICE  :: RHO_D,VX_D,VZ_D,ENE_D,PRE_D
REAL(KIND=C_DOUBLE),ALLOCATABLE,DIMENSION(:,:,:,:),DEVICE:: CENTERS_D

!SETUP GRID AND BLOCKS FOR THE KERNEL
PRINT*,'INITIAL CONDITION START'
TBLOCK=DIM3(8,4,8)
GRID=DIM3(CEILING(REAL(NX)/TBLOCK%X),CEILING(REAL(NY)/TBLOCK%Y),CEILING(REAL(NZ)/TBLOCK%Z))
PRINT*,'BLOCK CONFIG=',TBLOCK
PRINT*,'GRID CONFIG =',GRID

GAMA=1.4d0

SELECT CASE(CI_TYPE)

CASE(0) !0=2D
RHO=0.0d0
PRE=0.0d0
VX=0.0d0
VY=0.0d0
VZ=0.0d0
ENE=0.0d0

!COPY DATA HOST->DEVICE
ALLOCATE(RHO_D(NX,NY,NZ),VX_D(NX,NY,NZ),VZ_D(NX,NY,NZ),PRE_D(NX,NY,NZ),ENE_D(NX,NY,NZ),CENTERS_D(NX,NY,NZ,3))
RHO_D=RHO
PRE_D=PRE
ENE_D=ENE
VX_D=VX
VZ_D=VZ
CENTERS_D=CENTERS

!INITIAL CONDITION STEP ON DEVICE
CALL STEP<<<GRID,TBLOCK>>>(RHO_D,PRE_D,ENE_D,VX_D,VZ_D,CENTERS_D,NX,NY,NZ)

!COPY DATA DEVICE->HOST
RHO=RHO_D
PRE=PRE_D
ENE=ENE_D
VX=VX_D
VZ=VZ_D


DEALLOCATE(RHO_D(NX,NY,NZ),VX_D(NX,NY,NZ),VZ_D(NX,NY,NZ),PRE_D(NX,NY,NZ),ENE_D(NX,NY,NZ),CENTERS_D(NX,NY,NZ,3))

CASE(1) !1=LOAD FILES

OPEN(1,FILE='IC/RHO_ID.DAT',STATUS='OLD',FORM='UNFORMATTED')!FORM='UNFORMATTED',ACCESS='STREAM')
READ(1) RHO
CLOSE(1)

OPEN(1,FILE='IC/VX_ID.DAT',STATUS='OLD',FORM='UNFORMATTED')!FORM='UNFORMATTED',ACCESS='STREAM')
READ(1) VX
CLOSE(1)

OPEN(1,FILE='IC/VY_ID.DAT',STATUS='OLD',FORM='UNFORMATTED')!FORM='UNFORMATTED',ACCESS='STREAM')
READ(1) VY
CLOSE(1)

OPEN(1,FILE='IC/VZ_ID.DAT',STATUS='OLD',FORM='UNFORMATTED')!FORM='UNFORMATTED',ACCESS='STREAM')
READ(1) VZ
CLOSE(1)

OPEN(1,FILE='IC/PRE_ID.DAT',STATUS='OLD',FORM='UNFORMATTED')!FORM='UNFORMATTED',ACCESS='STREAM')
READ(1) PRE
CLOSE(1)

ENE=0.0d0
DO K=1,NZ
DO J=1,NY
DO I=1,NX
IF ((BOUNDS(I,J,K)==0)) THEN
ENE(I,J,K)=PRE(I,J,K)/0.4d0+0.5d0*RHO(I,J,K)*(VX(I,J,K)**2.0d0+VY(I,J,K)**2.0d0+VZ(I,J,K)**2.0d0) !PRE/(GAMA-1)+0.5*RHO*V**2
END IF
END DO
END DO
END DO

END SELECT

END SUBROUTINE