!INITAL CONDITION FOR CUBE MESH CUDA MODULES (PEDRO GODOI 2025)
MODULE COND_INITIAL_CUBE_CUDA
CONTAINS

ATTRIBUTES(GLOBAL) SUBROUTINE STEP(RHO_D,PRE_D,ENE_D,VX_D,VZ_D,CENTERS_D,NX,NY,NZ)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE) 	  :: RHO_D(:,:,:),PRE_D(:,:,:),ENE_D(:,:,:),VX_D(:,:,:),VZ_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: CENTERS_D(:,:,:,:)
INTEGER(KIND=C_INT) 	  :: I,J,K

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

IF ((I<NX) .AND. (J<NY) .AND. (K<NZ)) THEN
IF (CENTERS_D(I,J,K,1)>0.5d0)THEN
IF (CENTERS_D(I,J,K,3)>0.5d0) THEN !QUAD 1
RHO_D(I,J,K)=1.0d0
VX_D(I,J,K)=-0.75d0
VZ_D(I,J,K)=-0.5d0
PRE_D(I,J,K)=1.0d0
ELSE !QUAD 4
RHO_D(I,J,K)=3.0d0
VX_D(I,J,K)=0.75d0
VZ_D(I,J,K)=-0.5d0
PRE_D(I,J,K)=1.0d0
END IF
ELSE
IF (CENTERS_D(I,J,K,3)>0.5d0) THEN !QUAD 2
RHO_D(I,J,K)=2.0d0
VX_D(I,J,K)=-0.75d0
VZ_D(I,J,K)=0.5d0
PRE_D(I,J,K)=1.0d0
ELSE !QUAD 3
RHO_D(I,J,K)=1.0d0
VX_D(I,J,K)=0.75d0
VZ_D(I,J,K)=0.5d0
PRE_D(I,J,K)=1.0d0
END IF
END IF
ENE_D=PRE_D(I,J,K)/0.4d0+0.5d0*RHO_D(I,J,K)*(VX_D(I,J,K)**2.0d0+VZ_D(I,J,K)**2.0d0) !PRE/(GAMA-1)+0.5*RHO*V**2
END IF

END SUBROUTINE STEP

END MODULE