!SEMI-DISCRETE LE3D FOR CUBE MESH (PEDRO GODOI 2025)
SUBROUTINE LE3D_CUBE_SEMI(T0,TF,CFL_BASE,NX,NY,NZ,BORDER_TYPE,DIST_MAX,AREAS,VOLUMES,&
FLUX_TYPE,FLUX_DATA,ANIMA_FRAME,CENTERS,RHO,VX,VY,VZ,ENE,PRE,BOUNDS)

USE CUDAFOR
USE ISO_C_BINDING
USE LE3DSCHEME

!IMPLICIT NONE
!INPUT
REAL(KIND=C_DOUBLE),INTENT(IN)                           		 :: T0,TF,CFL_BASE,DIST_MAX,VOLUMES
INTEGER(KIND=C_INT),INTENT(IN)                         		     :: NX,NY,NZ,FLUX_TYPE,ANIMA_FRAME,BORDER_TYPE
REAL(KIND=C_DOUBLE),DIMENSION(3),INTENT(IN)              		 :: FLUX_DATA
REAL(KIND=C_DOUBLE),DIMENSION(6),INTENT(IN)              		 :: AREAS
REAL(KIND=C_DOUBLE),DIMENSION(NX,NY,NZ,3),INTENT(IN)     		 :: CENTERS
INTEGER(KIND=C_INT),DIMENSION(NX,NY,NZ),INTENT(IN)				 :: BOUNDS
!INPUT-OUTPUT
REAL(KIND=C_DOUBLE),DIMENSION(NX,NY,NZ),INTENT(INOUT)    :: RHO,VX,VY,VZ,ENE,PRE
!LOCAL VARIABLES
INTEGER(KIND=C_INT)										 :: I,J,K,L,FRAME,FRAME_COUNT,MPI_ERR,EQN,A,BACKUP
REAL(KIND=C_DOUBLE),DIMENSION(6,3)						 :: N
CHARACTER(KIND=C_CHAR,LEN=8)               			     :: FRAME_STR
LOGICAL(KIND=C_BOOL)                          			 :: ENDPOINT
REAL(KIND=C_DOUBLE),DIMENSION(NX,NY,NZ)					 :: RVX,RVY,RVZ
!REAL(KIND=C_DOUBLE),DIMENSION(NX,NY,NZ)					 :: RHO_ANT,RVX_ANT,RVY_ANT,RVZ_ANT,ENE_ANT
REAL(KIND=C_DOUBLE)							    		 :: P1,P2,P3,P4,P5,P6,GAMA
REAL(KIND=C_DOUBLE)										 :: SUP,SUP_P,DELTA_T,T,DIVB_SUP
REAL(KIND=C_DOUBLE),DIMENSION(3)						 :: DUMMY3
TYPE(DIM3)				  								 :: GRID, TBLOCK !CUDA
!DEVICE VARIABLES
INTEGER(KIND=C_INT),ALLOCATABLE,DIMENSION(:,:,:),DEVICE  :: BOUNDS_D
REAL(KIND=C_DOUBLE),ALLOCATABLE,DIMENSION(:,:,:),DEVICE  :: RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D
REAL(KIND=C_DOUBLE),ALLOCATABLE,DIMENSION(:,:,:),DEVICE  :: RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D
REAL(KIND=C_DOUBLE),ALLOCATABLE,DIMENSION(:,:,:),DEVICE  :: RHO_ANT2_D,RVX_ANT2_D,RVY_ANT2_D,RVZ_ANT2_D,ENE_ANT2_D
REAL(KIND=C_DOUBLE),ALLOCATABLE,DIMENSION(:,:,:,:),DEVICE:: SLOPES_D


!!!SETUP GRID AND BLOCKS FOR THE KERNEL
PRINT*,'LE3D CUBE SEMI-DISCRETE CUDA'
TBLOCK=DIM3(8,4,8)
GRID=DIM3(CEILING(REAL(NX)/TBLOCK%X),CEILING(REAL(NY)/TBLOCK%Y),CEILING(REAL(NZ)/TBLOCK%Z))
PRINT*,'BLOCK CONFIG=',TBLOCK
PRINT*,'GRID CONFIG =',GRID

!!!ALLOCATE DEVICE DATA
ALLOCATE(RHO_D(NX,NY,NZ),RVX_D(NX,NY,NZ),RVY_D(NX,NY,NZ),RVZ_D(NX,NY,NZ),ENE_D(NX,NY,NZ))
ALLOCATE(RHO_ANT_D(NX,NY,NZ),RVX_ANT_D(NX,NY,NZ),RVY_ANT_D(NX,NY,NZ),RVZ_ANT_D(NX,NY,NZ),ENE_ANT_D(NX,NY,NZ))
ALLOCATE(RHO_ANT2_D(NX,NY,NZ),RVX_ANT2_D(NX,NY,NZ),RVY_ANT2_D(NX,NY,NZ),RVZ_ANT2_D(NX,NY,NZ),ENE_ANT2_D(NX,NY,NZ))
ALLOCATE(PRE_D(NX,NY,NZ),VX_D(NX,NY,NZ),VY_D(NX,NY,NZ),VZ_D(NX,NY,NZ),BOUNDS_D(NX,NY,NZ),SLOPES_D(NX,NY,NZ,3))

!!!AUXILIARY VALUES
GAMA=1.4d0
BACKUP=0
!FACE SURFACE NORMALS
N(1,:)=(/-1.0d0,0.0d0,0.0d0/)  !NORMAL X-
N(2,:)=(/1.0d0,0.d0,0.0d0/)    !NORMAL X+
N(3,:)=(/0.0d0,-1.0d0,0.0d0/)  !NORMAL Y-
N(4,:)=(/0.0d0,1.0d0,0.0d0/)   !NORMAL Y+
N(5,:)=(/0.0d0,0.0d0,-1.0d0/)  !NORMAL Z-
N(6,:)=(/0.0d0,0.0d0,1.0d0/)   !NORMAL Z+

!SUP (FU/U)
SUP=0.0d0
DUMMY3=(/ MAXVAL(ABS(VX)) , MAXVAL(ABS(VY)) , MAXVAL(ABS(VZ)) /)
SUP=MAXVAL(ABS(DUMMY3))

!DELTA_T
DELTA_T=(CFL_BASE*DIST_MAX)/SUP
PRINT*,0.0d0,SUP,DELTA_T


!INITIAL ADJUSTEMENTS
T=T0+DELTA_T	         !ADJUSTS TIME
FRAME_COUNT=1	         !ANIMATION FRAME COUNTER
FRAME=1			         !CURRENT ANIMATION FRAME
ENDPOINT=.FALSE.	     !SET ENDPOINT TO FALSE (NOT REACHED)

!BOUNDARIES
!NEUMANN (OUTFLOW)
RHO(NX,:,:)=RHO(NX-1,:,:)
VX(NX,:,:)=VX(NX-1,:,:)
VY(NX,:,:)=VY(NX-1,:,:)
VZ(NX,:,:)=VZ(NX-1,:,:)
PRE(NX,:,:)=PRE(NX-1,:,:)
ENE(NX,:,:)=ENE(NX-1,:,:)

!PERIODIC
RHO(:,1,:)=RHO(:,NY-1,:)
VX(:,1,:)=VX(:,NY-1,:)
VY(:,1,:)=VY(:,NY-1,:)
VZ(:,1,:)=VZ(:,NY-1,:)
PRE(:,1,:)=PRE(:,NY-1,:)
ENE(:,1,:)=ENE(:,NY-1,:)

RHO(:,NY,:)=RHO(:,2,:)
VX(:,NY,:)=VX(:,2,:)
VY(:,NY,:)=VY(:,2,:)
VZ(:,NY,:)=VZ(:,2,:)
PRE(:,NY,:)=PRE(:,2,:)
ENE(:,NY,:)=ENE(:,2,:)

!CREATE RHO*VELOCITY
RVX=0.0d0
RVY=0.0d0
RVZ=0.0d0

!COPY DATA HOST->DEVICE
RHO_D=RHO
ENE_D=ENE
PRE_D=PRE
VX_D=VX
VY_D=VY
VZ_D=VZ
RVX_D=RVX
RVY_D=RVY
RVZ_D=RVZ
BOUNDS_D=BOUNDS

!RECOVER MOMENTUM ON DEVICE
CALL MOMENTUM<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,VX_D,VY_D,VZ_D,BOUNDS_D,NX,NY,NZ)

!COPY DATA DEVICE->HOST
RVX=RVX_D
RVY=RVY_D
RVZ=RVZ_D

!PRINT*,MAXVAL(RVX)

!ANTERIOR VALUES
RHO_ANT_D=RHO_D
RVX_ANT_D=RVX_D
RVY_ANT_D=RVY_D
RVZ_ANT_D=RVZ_D
ENE_ANT_D=ENE_D
RHO_ANT2_D=RHO_D
RVX_ANT2_D=RVX_D
RVY_ANT2_D=RVY_D
RVZ_ANT2_D=RVZ_D
ENE_ANT2_D=ENE_D
SLOPES_D=0.0d0

!DEBUG
!PRINT*,NORM2(RHO)

!!!LE3D FULLY-DISCRETE
DO !A=1,1!WHILE ENDPOINT==FALSE

!!!RK-SHU FIRST STEP
!RHO
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(RHO_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,1.0d0,1.0d0)
CALL SCHEME1<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))
!RVX
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(RVX_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,-1.0d0,1.0d0)
CALL SCHEME2<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))
!RVY
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(RVY_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,1.0d0,1.0d0)
CALL SCHEME3<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))
!RVZ
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(RVZ_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,1.0d0,-1.0d0)
CALL SCHEME4<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))
!ENE
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(ENE_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,1.0d0,1.0d0)
CALL SCHEME5<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))

!COPY DATA DEVICE->HOST
RHO=RHO_D
RVX=RVX_D
RVY=RVY_D
RVZ=RVZ_D
ENE=ENE_D

!NEUMANN (OUTFLOW)
RHO(NX,:,:)=RHO(NX-1,:,:)
RVX(NX,:,:)=RVX(NX-1,:,:)
RVY(NX,:,:)=RVY(NX-1,:,:)
RVZ(NX,:,:)=RVZ(NX-1,:,:)
ENE(NX,:,:)=ENE(NX-1,:,:)

RHO(:,:,1)=RHO(:,:,2)
RVX(:,:,1)=RVX(:,:,2)
RVY(:,:,1)=RVY(:,:,2)
RVZ(:,:,1)=RVZ(:,:,2)
ENE(:,:,1)=ENE(:,:,2)

RHO(:,:,NZ)=RHO(:,:,NZ-1)
RVX(:,:,NZ)=RVX(:,:,NZ-1)
RVY(:,:,NZ)=RVY(:,:,NZ-1)
RVZ(:,:,NZ)=RVZ(:,:,NZ-1)
ENE(:,:,NZ)=ENE(:,:,NZ-1)

!PERIODIC
RHO(:,1,:)=RHO(:,NY-1,:)
RVX(:,1,:)=RVX(:,NY-1,:)
RVY(:,1,:)=RVY(:,NY-1,:)
RVZ(:,1,:)=RVZ(:,NY-1,:)
ENE(:,1,:)=ENE(:,NY-1,:)

RHO(:,NY,:)=RHO(:,2,:)
RVX(:,NY,:)=RVX(:,2,:)
RVY(:,NY,:)=RVY(:,2,:)
RVZ(:,NY,:)=RVZ(:,2,:)
ENE(:,NY,:)=ENE(:,2,:)


!COPY DATA HOST->DEVICE
RHO_D=RHO
ENE_D=ENE
RVX_D=RVX
RVY_D=RVY
RVZ_D=RVZ

!RECOVER PRESSURE AND VELOCITIES ON DEVICE
CALL PRESSURE<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,VX_D,VY_D,VZ_D,BOUNDS_D,NX,NY,NZ,PRE_D,ENE_D)

!COPY DATA DEVICE->HOST
VX=VX_D
VY=VY_D
VZ=VZ_D
PRE=PRE_D

!ANTERIOR VALUES
RHO_ANT_D=RHO_D
RVX_ANT_D=RVX_D
RVY_ANT_D=RVY_D
RVZ_ANT_D=RVZ_D
ENE_ANT_D=ENE_D

!!!RK-SHU SECOND STEP
!RHO
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(RHO_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,1.0d0,1.0d0)
CALL SCHEME1<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))
!RVX
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(RVX_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,-1.0d0,1.0d0)
CALL SCHEME2<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))
!RVY
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(RVY_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,1.0d0,1.0d0)
CALL SCHEME3<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))
!RVZ
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(RVZ_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,1.0d0,-1.0d0)
CALL SCHEME4<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))
!ENE
CALL SLOPELIMITER<<<GRID,TBLOCK>>>(ENE_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,2.0d0,1.65d0,1.0d0,1.0d0)
CALL SCHEME5<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS(1),AREAS(2),AREAS(3),AREAS(4),AREAS(5),AREAS(6))

!!!RK-SHU CONSOLIDATION

CALL RKCONSOLIDATE<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,&
RHO_ANT2_D,RVX_ANT2_D,RVY_ANT2_D,RVZ_ANT2_D,ENE_ANT2_D,BOUNDS_D,NX,NY,NZ)

!COPY DATA DEVICE->HOST
RHO=RHO_D
RVX=RVX_D
RVY=RVY_D
RVZ=RVZ_D
ENE=ENE_D

!NEUMANN (OUTFLOW)
RHO(NX,:,:)=RHO(NX-1,:,:)
RVX(NX,:,:)=RVX(NX-1,:,:)
RVY(NX,:,:)=RVY(NX-1,:,:)
RVZ(NX,:,:)=RVZ(NX-1,:,:)
ENE(NX,:,:)=ENE(NX-1,:,:)

RHO(:,:,1)=RHO(:,:,2)
RVX(:,:,1)=RVX(:,:,2)
RVY(:,:,1)=RVY(:,:,2)
RVZ(:,:,1)=RVZ(:,:,2)
ENE(:,:,1)=ENE(:,:,2)

RHO(:,:,NZ)=RHO(:,:,NZ-1)
RVX(:,:,NZ)=RVX(:,:,NZ-1)
RVY(:,:,NZ)=RVY(:,:,NZ-1)
RVZ(:,:,NZ)=RVZ(:,:,NZ-1)
ENE(:,:,NZ)=ENE(:,:,NZ-1)

!PERIODIC
RHO(:,1,:)=RHO(:,NY-1,:)
RVX(:,1,:)=RVX(:,NY-1,:)
RVY(:,1,:)=RVY(:,NY-1,:)
RVZ(:,1,:)=RVZ(:,NY-1,:)
ENE(:,1,:)=ENE(:,NY-1,:)

RHO(:,NY,:)=RHO(:,2,:)
RVX(:,NY,:)=RVX(:,2,:)
RVY(:,NY,:)=RVY(:,2,:)
RVZ(:,NY,:)=RVZ(:,2,:)
ENE(:,NY,:)=ENE(:,2,:)


!COPY DATA HOST->DEVICE
RHO_D=RHO
ENE_D=ENE
RVX_D=RVX
RVY_D=RVY
RVZ_D=RVZ

!RECOVER PRESSURE AND VELOCITIES ON DEVICE
CALL PRESSURE<<<GRID,TBLOCK>>>(RHO_D,RVX_D,RVY_D,RVZ_D,VX_D,VY_D,VZ_D,BOUNDS_D,NX,NY,NZ,PRE_D,ENE_D)

!COPY DATA DEVICE->HOST
VX=VX_D
VY=VY_D
VZ=VZ_D
PRE=PRE_D

!SUP (FU/U)
SUP=0.0d0
DUMMY3=(/ MAXVAL(ABS(VX)) , MAXVAL(ABS(VY)) , MAXVAL(ABS(VZ)) /)
SUP=MAXVAL(ABS(DUMMY3))

!DELTA_T
DELTA_T=(CFL_BASE*DIST_MAX)/SUP
PRINT*,T,SUP,DELTA_T

!VERIFIES ENDPOINT STATUS
IF (ENDPOINT) EXIT

!ADJUST NEXT TIME
IF (T+DELTA_T>=TF) THEN
DELTA_T=TF-T
ENDPOINT=.TRUE.
END IF

T=T+DELTA_T

!ANTERIOR VALUES
RHO_ANT_D=RHO_D
RVX_ANT_D=RVX_D
RVY_ANT_D=RVY_D
RVZ_ANT_D=RVZ_D
ENE_ANT_D=ENE_D
RHO_ANT2_D=RHO_D
RVX_ANT2_D=RVX_D
RVY_ANT2_D=RVY_D
RVZ_ANT2_D=RVZ_D
ENE_ANT2_D=ENE_D

!SAVE ANIMATION
IF (FRAME_COUNT==ANIMA_FRAME) THEN										!VERIFY FRAMESKIP
FRAME_COUNT=0															!RESET FRAME COUNTER
IF (ANIMA_FRAME>0) THEN
CALL GNUPLOT_CUBE(NX,NY,NZ,FRAME,0,CENTERS,RHO,PRE,VX,VY,VZ,BOUNDS)
FRAME=FRAME+1
END IF
END IF

!SAVE BACKUP
IF (BACKUP==10000) THEN
BACKUP = SYSTEM('rm -r OUTPUT/BACKUP')
BACKUP = SYSTEM('mkdir OUTPUT/BACKUP')
OPEN(2,FILE='OUTPUT/BACKUP/RHO.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) RHO
WRITE(2) I,RHO,I
CLOSE(2)

OPEN(2,FILE='OUTPUT/BACKUP/VX.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) VX
WRITE(2) I,VX,I
CLOSE(2)

OPEN(2,FILE='OUTPUT/BACKUP/VY.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) VY
WRITE(2) I,VY,I
CLOSE(2)

OPEN(2,FILE='OUTPUT/BACKUP/VZ.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) VZ
WRITE(2) I,VZ,I
CLOSE(2)

OPEN(2,FILE='OUTPUT/BACKUP/PRE_ID.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) PRE
WRITE(2) I,PRE,I
CLOSE(2)

OPEN(2,FILE='OUTPUT/BACKUP/T.DAT',STATUS='NEW')
WRITE(2,'(E20.12)') T
CLOSE(2)

BACKUP=0
END IF

FRAME_COUNT=FRAME_COUNT+1
BACKUP=BACKUP+1

END DO !WHILE ENDPOINT==FALSE

!COPY DATA DEVICE->HOST
RHO=RHO_D
VX=VX_D
VY=VY_D
VZ=VZ_D
ENE=ENE_D
PRE=PRE_D

! !SAVE LAST FRAME
CALL GNUPLOT_CUBE(NX,NY,NZ,FRAME,0,CENTERS,RHO,PRE,VX,VY,VZ,BOUNDS)

!DEBUG
!PRINT*,NORM2(RHO)

!DEALLOCATE DEVICE DATA
DEALLOCATE(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D)
DEALLOCATE(RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D)
DEALLOCATE(PRE_D,VX_D,VY_D,VZ_D)

END SUBROUTINE