!LE3D SCHEME CUDA (PEDRO GODOI 2025)
MODULE LE3DSCHEME
CONTAINS

ATTRIBUTES(GLOBAL) SUBROUTINE MOMENTUM(RHO_D,RVX_D,RVY_D,RVZ_D,VX_D,VY_D,VZ_D,BOUNDS_D,NX,NY,NZ)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE) 	  :: RHO_D(:,:,:),RVX_D(:,:,:),RVY_D(:,:,:),RVZ_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: VX_D(:,:,:),VY_D(:,:,:),VZ_D(:,:,:)
INTEGER(KIND=C_INT) 	  :: BOUNDS_D(:,:,:)
INTEGER(KIND=C_INT) 	  :: I,J,K

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

IF ((I<=NX) .AND. (J<=NY) .AND. (K<=NZ)) THEN
IF(BOUNDS_D(I,J,K)==0) THEN
RVX_D(I,J,K)=RHO_D(I,J,K)*VX_D(I,J,K)
RVY_D(I,J,K)=RHO_D(I,J,K)*VY_D(I,J,K)
RVZ_D(I,J,K)=RHO_D(I,J,K)*VZ_D(I,J,K)
END IF
END IF

END SUBROUTINE MOMENTUM

ATTRIBUTES(GLOBAL) SUBROUTINE SCHEME1(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE) 	  :: RHO_D(:,:,:),RVX_D(:,:,:),RVY_D(:,:,:),RVZ_D(:,:,:),ENE_D(:,:,:),PRE_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: VX_D(:,:,:),VY_D(:,:,:),VZ_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: RHO_ANT_D(:,:,:),RVX_ANT_D(:,:,:),RVY_ANT_D(:,:,:),RVZ_ANT_D(:,:,:),ENE_ANT_D(:,:,:)
REAL(KIND=C_DOUBLE),VALUE :: DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6,DIST_MAX
INTEGER(KIND=C_INT) 	  :: BOUNDS_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: SLOPES_D(:,:,:,:)
!LOCAL VARIABLES
INTEGER(KIND=C_INT) 	          :: I,J,K,L
REAL(KIND=C_DOUBLE),DIMENSION(6)  :: RHO_V,RVX_V,RVY_V,RVZ_V,VX_V,VY_V,VZ_V,ENE_V,PRE_V
REAL(KIND=C_DOUBLE),DIMENSION(6,3):: N
REAL(KIND=C_DOUBLE)				  :: P1,P2,P3,P4,P5,P6,U_PLUS,U_MINUS,XI
REAL(KIND=C_DOUBLE),DIMENSION(3)  :: FUK,FUL1,FUL2,FUL3,FUL4,FUL5,FUL6,BUK,BUL1,BUL2,BUL3,BUL4,BUL5,BUL6

XI=2.0d0

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

!FACE SURFACE NORMALS
N(1,:)=(/-1.0d0,0.0d0,0.0d0/)  !NORMAL X-
N(2,:)=(/1.0d0,0.d0,0.0d0/)    !NORMAL X+
N(3,:)=(/0.0d0,-1.0d0,0.0d0/)  !NORMAL Y-
N(4,:)=(/0.0d0,1.0d0,0.0d0/)   !NORMAL Y+
N(5,:)=(/0.0d0,0.0d0,-1.0d0/)  !NORMAL Z-
N(6,:)=(/0.0d0,0.0d0,1.0d0/)   !NORMAL Z+

IF ((I>1) .AND. (I<NX) .AND. (J>1) .AND. (J<NY) .AND. (K>1) .AND. (K<NZ)) THEN
IF (BOUNDS_D(I,J,K)==0) THEN

!NEIGHBORS
RHO_V(1)=RHO_ANT_D(I-1,J,K)
 VX_V(1)=     VX_D(I-1,J,K)
 VY_V(1)=     VY_D(I-1,J,K)
 VZ_V(1)=     VZ_D(I-1,J,K)
ENE_V(1)=ENE_ANT_D(I-1,J,K)
PRE_V(1)=    PRE_D(I-1,J,K)
RVX_V(1)=RVX_ANT_D(I-1,J,K)
RVY_V(1)=RVY_ANT_D(I-1,J,K)
RVZ_V(1)=RVZ_ANT_D(I-1,J,K)

RHO_V(2)=RHO_ANT_D(I+1,J,K)
 VX_V(2)=     VX_D(I+1,J,K)
 VY_V(2)=     VY_D(I+1,J,K)
 VZ_V(2)=     VZ_D(I+1,J,K)
ENE_V(2)=ENE_ANT_D(I+1,J,K)
PRE_V(2)=    PRE_D(I+1,J,K)
RVX_V(2)=RVX_ANT_D(I+1,J,K)
RVY_V(2)=RVY_ANT_D(I+1,J,K)
RVZ_V(2)=RVZ_ANT_D(I+1,J,K)

RHO_V(3)=RHO_ANT_D(I,J-1,K)
 VX_V(3)=     VX_D(I,J-1,K)
 VY_V(3)=     VY_D(I,J-1,K)
 VZ_V(3)=     VZ_D(I,J-1,K)
ENE_V(3)=ENE_ANT_D(I,J-1,K)
PRE_V(3)=    PRE_D(I,J-1,K)
RVX_V(3)=RVX_ANT_D(I,J-1,K)
RVY_V(3)=RVY_ANT_D(I,J-1,K)
RVZ_V(3)=RVZ_ANT_D(I,J-1,K)

RHO_V(4)=RHO_ANT_D(I,J+1,K)
 VX_V(4)=     VX_D(I,J+1,K)
 VY_V(4)=     VY_D(I,J+1,K)
 VZ_V(4)=     VZ_D(I,J+1,K)
ENE_V(4)=ENE_ANT_D(I,J+1,K)
PRE_V(4)=    PRE_D(I,J+1,K)
RVX_V(4)=RVX_ANT_D(I,J+1,K)
RVY_V(4)=RVY_ANT_D(I,J+1,K)
RVZ_V(4)=RVZ_ANT_D(I,J+1,K)

RHO_V(5)=RHO_ANT_D(I,J,K-1)
 VX_V(5)=     VX_D(I,J,K-1)
 VY_V(5)=     VY_D(I,J,K-1)
 VZ_V(5)=     VZ_D(I,J,K-1)
ENE_V(5)=ENE_ANT_D(I,J,K-1)
PRE_V(5)=    PRE_D(I,J,K-1)
RVX_V(5)=RVX_ANT_D(I,J,K-1)
RVY_V(5)=RVY_ANT_D(I,J,K-1)
RVZ_V(5)=RVZ_ANT_D(I,J,K-1)

RHO_V(6)=RHO_ANT_D(I,J,K+1)
 VX_V(6)=     VX_D(I,J,K+1)
 VY_V(6)=     VY_D(I,J,K+1)
 VZ_V(6)=     VZ_D(I,J,K+1)
ENE_V(6)=ENE_ANT_D(I,J,K+1)
PRE_V(6)=    PRE_D(I,J,K+1)
RVX_V(6)=RVX_ANT_D(I,J,K+1)
RVY_V(6)=RVY_ANT_D(I,J,K+1)
RVZ_V(6)=RVZ_ANT_D(I,J,K+1)

IF(BOUNDS_D(I-1,J,K)==1) THEN !REFLECTIVE WALL RIGHT
RHO_V(1)=RHO_ANT_D(I,J,K)
RVX_V(1)=-RVX_ANT_D(I,J,K)
RVY_V(1)=RVY_ANT_D(I,J,K)
RVZ_V(1)=RVZ_ANT_D(I,J,K)
ENE_V(1)=ENE_ANT_D(I,J,K)
PRE_V(1)=PRE_D(I,J,K)

VX_V(1)=RVX_V(1)/RHO_V(1)
VY_V(1)=RVY_V(1)/RHO_V(1)
VZ_V(1)=RVZ_V(1)/RHO_V(1)
END IF

IF(BOUNDS_D(I+1,J,K)==1) THEN !REFLECTIVE WALL LEFT
RHO_V(2)=RHO_ANT_D(I,J,K)
RVX_V(2)=-RVX_ANT_D(I,J,K)
RVY_V(2)=RVY_ANT_D(I,J,K)
RVZ_V(2)=RVZ_ANT_D(I,J,K)
ENE_V(2)=ENE_ANT_D(I,J,K)
PRE_V(2)=PRE_D(I,J,K)

VX_V(2)=RVX_V(2)/RHO_V(2)
VY_V(2)=RVY_V(2)/RHO_V(2)
VZ_V(2)=RVZ_V(2)/RHO_V(2)
END IF

IF(BOUNDS_D(I,J,K-1)==1) THEN !REFLECTIVE FLOOR
RHO_V(5)=RHO_ANT_D(I,J,K)
RVX_V(5)=RVX_ANT_D(I,J,K)
RVY_V(5)=RVY_ANT_D(I,J,K)
RVZ_V(5)=-RVZ_ANT_D(I,J,K)
ENE_V(5)=ENE_ANT_D(I,J,K)
PRE_V(5)=PRE_D(I,J,K)

VX_V(5)=RVX_V(5)/RHO_V(5)
VY_V(5)=RVY_V(5)/RHO_V(5)
VZ_V(5)=RVZ_V(5)/RHO_V(5)
END IF

IF(BOUNDS_D(I,J,K+1)==1) THEN !REFLECTIVE CEIL
RHO_V(6)=RHO_ANT_D(I,J,K)
RVX_V(6)=RVX_ANT_D(I,J,K)
RVY_V(6)=RVY_ANT_D(I,J,K)
RVZ_V(6)=-RVZ_ANT_D(I,J,K)
ENE_V(6)=ENE_ANT_D(I,J,K)
PRE_V(6)=PRE_D(I,J,K)

VX_V(6)=RVX_V(6)/RHO_V(6)
VY_V(6)=RVY_V(6)/RHO_V(6)
VZ_V(6)=RVZ_V(6)/RHO_V(6)
END IF

!!!EQUATION 1 RHO
FUK=(/VX_D(I,J,K) , VY_D(I,J,K) , VZ_D(I,J,K)/)

!X+
U_PLUS=RHO_V(2)-(DIST_MAX/4.0d0)*SLOPES_D(I+1,J,K,1)
U_MINUS=RHO_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
FUL2=(/VX_V(2) , VY_V(2) , VZ_V(2)/)
P2=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL2(1))*(U_MINUS+U_PLUS)))*AREAS2

!X-
U_PLUS=RHO_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
U_MINUS=RHO_V(1)+(DIST_MAX/4.0d0)*SLOPES_D(I-1,J,K,1)
FUL1=(/VX_V(1) , VY_V(1) , VZ_V(1)/)
P1=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL1(1))*(U_MINUS+U_PLUS)))*AREAS1

!Y+
U_PLUS=RHO_V(4)-(DIST_MAX/4.0d0)*SLOPES_D(I,J+1,K,2)
U_MINUS=RHO_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
FUL4=(/VX_V(4) , VY_V(4) , VZ_V(4)/)
P4=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL4(2))*(U_MINUS+U_PLUS)))*AREAS4

!Y-
U_PLUS=RHO_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
U_MINUS=RHO_V(3)+(DIST_MAX/4.0d0)*SLOPES_D(I,J-1,K,2)
FUL3=(/VX_V(3) , VY_V(3) , VZ_V(3)/)
P3=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL3(2))*(U_MINUS+U_PLUS)))*AREAS3

!Z+
U_PLUS=RHO_V(6)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K+1,3)
U_MINUS=RHO_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
FUL6=(/VX_V(6) , VY_V(6) , VZ_V(6)/)
P6=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL6(3))*(U_MINUS+U_PLUS)))*AREAS6

!Z-
U_PLUS=RHO_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
U_MINUS=RHO_V(5)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K-1,3)
FUL5=(/VX_V(5) , VY_V(5) , VZ_V(5)/)
P5=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL5(3))*(U_MINUS+U_PLUS)))*AREAS5

RHO_D(I,J,K)=RHO_ANT_D(I,J,K)-(DELTA_T/VOLUMES)*(P1+P2+P3+P4+P5+P6)

END IF !BOUNDS

END IF
END SUBROUTINE SCHEME1

ATTRIBUTES(GLOBAL) SUBROUTINE SCHEME2(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE) 	  :: RHO_D(:,:,:),RVX_D(:,:,:),RVY_D(:,:,:),RVZ_D(:,:,:),ENE_D(:,:,:),PRE_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: VX_D(:,:,:),VY_D(:,:,:),VZ_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: RHO_ANT_D(:,:,:),RVX_ANT_D(:,:,:),RVY_ANT_D(:,:,:),RVZ_ANT_D(:,:,:),ENE_ANT_D(:,:,:)
REAL(KIND=C_DOUBLE),VALUE :: DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6,DIST_MAX
INTEGER(KIND=C_INT) 	  :: BOUNDS_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: SLOPES_D(:,:,:,:)
!LOCAL VARIABLES
INTEGER(KIND=C_INT) 	          :: I,J,K,L
REAL(KIND=C_DOUBLE),DIMENSION(6)  :: RHO_V,RVX_V,RVY_V,RVZ_V,VX_V,VY_V,VZ_V,ENE_V,PRE_V
REAL(KIND=C_DOUBLE),DIMENSION(6,3):: N
REAL(KIND=C_DOUBLE)				  :: P1,P2,P3,P4,P5,P6,U_PLUS,U_MINUS,XI
REAL(KIND=C_DOUBLE),DIMENSION(3)  :: FUK,FUL1,FUL2,FUL3,FUL4,FUL5,FUL6,BUK,BUL1,BUL2,BUL3,BUL4,BUL5,BUL6

XI=2.0d0

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

!FACE SURFACE NORMALS
N(1,:)=(/-1.0d0,0.0d0,0.0d0/)  !NORMAL X-
N(2,:)=(/1.0d0,0.d0,0.0d0/)    !NORMAL X+
N(3,:)=(/0.0d0,-1.0d0,0.0d0/)  !NORMAL Y-
N(4,:)=(/0.0d0,1.0d0,0.0d0/)   !NORMAL Y+
N(5,:)=(/0.0d0,0.0d0,-1.0d0/)  !NORMAL Z-
N(6,:)=(/0.0d0,0.0d0,1.0d0/)   !NORMAL Z+

IF ((I>1) .AND. (I<NX) .AND. (J>1) .AND. (J<NY) .AND. (K>1) .AND. (K<NZ)) THEN
IF (BOUNDS_D(I,J,K)==0) THEN

!NEIGHBORS
RHO_V(1)=RHO_ANT_D(I-1,J,K)
 VX_V(1)=     VX_D(I-1,J,K)
 VY_V(1)=     VY_D(I-1,J,K)
 VZ_V(1)=     VZ_D(I-1,J,K)
ENE_V(1)=ENE_ANT_D(I-1,J,K)
PRE_V(1)=    PRE_D(I-1,J,K)
RVX_V(1)=RVX_ANT_D(I-1,J,K)
RVY_V(1)=RVY_ANT_D(I-1,J,K)
RVZ_V(1)=RVZ_ANT_D(I-1,J,K)

RHO_V(2)=RHO_ANT_D(I+1,J,K)
 VX_V(2)=     VX_D(I+1,J,K)
 VY_V(2)=     VY_D(I+1,J,K)
 VZ_V(2)=     VZ_D(I+1,J,K)
ENE_V(2)=ENE_ANT_D(I+1,J,K)
PRE_V(2)=    PRE_D(I+1,J,K)
RVX_V(2)=RVX_ANT_D(I+1,J,K)
RVY_V(2)=RVY_ANT_D(I+1,J,K)
RVZ_V(2)=RVZ_ANT_D(I+1,J,K)

RHO_V(3)=RHO_ANT_D(I,J-1,K)
 VX_V(3)=     VX_D(I,J-1,K)
 VY_V(3)=     VY_D(I,J-1,K)
 VZ_V(3)=     VZ_D(I,J-1,K)
ENE_V(3)=ENE_ANT_D(I,J-1,K)
PRE_V(3)=    PRE_D(I,J-1,K)
RVX_V(3)=RVX_ANT_D(I,J-1,K)
RVY_V(3)=RVY_ANT_D(I,J-1,K)
RVZ_V(3)=RVZ_ANT_D(I,J-1,K)

RHO_V(4)=RHO_ANT_D(I,J+1,K)
 VX_V(4)=     VX_D(I,J+1,K)
 VY_V(4)=     VY_D(I,J+1,K)
 VZ_V(4)=     VZ_D(I,J+1,K)
ENE_V(4)=ENE_ANT_D(I,J+1,K)
PRE_V(4)=    PRE_D(I,J+1,K)
RVX_V(4)=RVX_ANT_D(I,J+1,K)
RVY_V(4)=RVY_ANT_D(I,J+1,K)
RVZ_V(4)=RVZ_ANT_D(I,J+1,K)

RHO_V(5)=RHO_ANT_D(I,J,K-1)
 VX_V(5)=     VX_D(I,J,K-1)
 VY_V(5)=     VY_D(I,J,K-1)
 VZ_V(5)=     VZ_D(I,J,K-1)
ENE_V(5)=ENE_ANT_D(I,J,K-1)
PRE_V(5)=    PRE_D(I,J,K-1)
RVX_V(5)=RVX_ANT_D(I,J,K-1)
RVY_V(5)=RVY_ANT_D(I,J,K-1)
RVZ_V(5)=RVZ_ANT_D(I,J,K-1)

RHO_V(6)=RHO_ANT_D(I,J,K+1)
 VX_V(6)=     VX_D(I,J,K+1)
 VY_V(6)=     VY_D(I,J,K+1)
 VZ_V(6)=     VZ_D(I,J,K+1)
ENE_V(6)=ENE_ANT_D(I,J,K+1)
PRE_V(6)=    PRE_D(I,J,K+1)
RVX_V(6)=RVX_ANT_D(I,J,K+1)
RVY_V(6)=RVY_ANT_D(I,J,K+1)
RVZ_V(6)=RVZ_ANT_D(I,J,K+1)

IF(BOUNDS_D(I-1,J,K)==1) THEN !REFLECTIVE WALL RIGHT
RHO_V(1)=RHO_ANT_D(I,J,K)
RVX_V(1)=-RVX_ANT_D(I,J,K)
RVY_V(1)=RVY_ANT_D(I,J,K)
RVZ_V(1)=RVZ_ANT_D(I,J,K)
ENE_V(1)=ENE_ANT_D(I,J,K)
PRE_V(1)=PRE_D(I,J,K)

VX_V(1)=RVX_V(1)/RHO_V(1)
VY_V(1)=RVY_V(1)/RHO_V(1)
VZ_V(1)=RVZ_V(1)/RHO_V(1)
END IF

IF(BOUNDS_D(I+1,J,K)==1) THEN !REFLECTIVE WALL LEFT
RHO_V(2)=RHO_ANT_D(I,J,K)
RVX_V(2)=-RVX_ANT_D(I,J,K)
RVY_V(2)=RVY_ANT_D(I,J,K)
RVZ_V(2)=RVZ_ANT_D(I,J,K)
ENE_V(2)=ENE_ANT_D(I,J,K)
PRE_V(2)=PRE_D(I,J,K)

VX_V(2)=RVX_V(2)/RHO_V(2)
VY_V(2)=RVY_V(2)/RHO_V(2)
VZ_V(2)=RVZ_V(2)/RHO_V(2)
END IF

IF(BOUNDS_D(I,J,K-1)==1) THEN !REFLECTIVE FLOOR
RHO_V(5)=RHO_ANT_D(I,J,K)
RVX_V(5)=RVX_ANT_D(I,J,K)
RVY_V(5)=RVY_ANT_D(I,J,K)
RVZ_V(5)=-RVZ_ANT_D(I,J,K)
ENE_V(5)=ENE_ANT_D(I,J,K)
PRE_V(5)=PRE_D(I,J,K)

VX_V(5)=RVX_V(5)/RHO_V(5)
VY_V(5)=RVY_V(5)/RHO_V(5)
VZ_V(5)=RVZ_V(5)/RHO_V(5)
END IF

IF(BOUNDS_D(I,J,K+1)==1) THEN !REFLECTIVE CEIL
RHO_V(6)=RHO_ANT_D(I,J,K)
RVX_V(6)=RVX_ANT_D(I,J,K)
RVY_V(6)=RVY_ANT_D(I,J,K)
RVZ_V(6)=-RVZ_ANT_D(I,J,K)
ENE_V(6)=ENE_ANT_D(I,J,K)
PRE_V(6)=PRE_D(I,J,K)

VX_V(6)=RVX_V(6)/RHO_V(6)
VY_V(6)=RVY_V(6)/RHO_V(6)
VZ_V(6)=RVZ_V(6)/RHO_V(6)
END IF

!!!EQUATION 2 RVX
FUK=(/VX_D(I,J,K) , VY_D(I,J,K) , VZ_D(I,J,K)/)

!X+
U_PLUS=RVX_V(2)-(DIST_MAX/4.0d0)*SLOPES_D(I+1,J,K,1)
U_MINUS=RVX_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
FUL2=(/VX_V(2) , VY_V(2) , VZ_V(2)/)
P2=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL2(1))*(U_MINUS+U_PLUS)) +0.5*(PRE_D(I,J,K)+PRE_V(2)))*AREAS2

!X-
U_PLUS=RVX_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
U_MINUS=RVX_V(1)+(DIST_MAX/4.0d0)*SLOPES_D(I-1,J,K,1)
FUL1=(/VX_V(1) , VY_V(1) , VZ_V(1)/)
P1=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL1(1))*(U_MINUS+U_PLUS)) +0.5*(PRE_D(I,J,K)+PRE_V(1)))*AREAS1

!Y+
U_PLUS=RVX_V(4)-(DIST_MAX/4.0d0)*SLOPES_D(I,J+1,K,2)
U_MINUS=RVX_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
FUL4=(/VX_V(4) , VY_V(4) , VZ_V(4)/)
P4=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL4(2))*(U_MINUS+U_PLUS)))*AREAS4

!Y-
U_PLUS=RVX_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
U_MINUS=RVX_V(3)+(DIST_MAX/4.0d0)*SLOPES_D(I,J-1,K,2)
FUL3=(/VX_V(3) , VY_V(3) , VZ_V(3)/)
P3=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL3(2))*(U_MINUS+U_PLUS)))*AREAS3

!Z+
U_PLUS=RVX_V(6)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K+1,3)
U_MINUS=RVX_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
FUL6=(/VX_V(6) , VY_V(6) , VZ_V(6)/)
P6=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL6(3))*(U_MINUS+U_PLUS)))*AREAS6

!Z-
U_PLUS=RVX_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
U_MINUS=RVX_V(5)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K-1,3)
FUL5=(/VX_V(5) , VY_V(5) , VZ_V(5)/)
P5=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL5(3))*(U_MINUS+U_PLUS)))*AREAS5

RVX_D(I,J,K)=RVX_ANT_D(I,J,K)-(DELTA_T/VOLUMES)*(P1+P2+P3+P4+P5+P6)


END IF !BOUNDS

END IF
END SUBROUTINE SCHEME2

ATTRIBUTES(GLOBAL) SUBROUTINE SCHEME3(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE) 	  :: RHO_D(:,:,:),RVX_D(:,:,:),RVY_D(:,:,:),RVZ_D(:,:,:),ENE_D(:,:,:),PRE_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: VX_D(:,:,:),VY_D(:,:,:),VZ_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: RHO_ANT_D(:,:,:),RVX_ANT_D(:,:,:),RVY_ANT_D(:,:,:),RVZ_ANT_D(:,:,:),ENE_ANT_D(:,:,:)
REAL(KIND=C_DOUBLE),VALUE :: DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6,DIST_MAX
INTEGER(KIND=C_INT) 	  :: BOUNDS_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: SLOPES_D(:,:,:,:)
!LOCAL VARIABLES
INTEGER(KIND=C_INT) 	          :: I,J,K,L
REAL(KIND=C_DOUBLE),DIMENSION(6)  :: RHO_V,RVX_V,RVY_V,RVZ_V,VX_V,VY_V,VZ_V,ENE_V,PRE_V
REAL(KIND=C_DOUBLE),DIMENSION(6,3):: N
REAL(KIND=C_DOUBLE)				  :: P1,P2,P3,P4,P5,P6,U_PLUS,U_MINUS,XI
REAL(KIND=C_DOUBLE),DIMENSION(3)  :: FUK,FUL1,FUL2,FUL3,FUL4,FUL5,FUL6,BUK,BUL1,BUL2,BUL3,BUL4,BUL5,BUL6

XI=2.0d0

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

!FACE SURFACE NORMALS
N(1,:)=(/-1.0d0,0.0d0,0.0d0/)  !NORMAL X-
N(2,:)=(/1.0d0,0.d0,0.0d0/)    !NORMAL X+
N(3,:)=(/0.0d0,-1.0d0,0.0d0/)  !NORMAL Y-
N(4,:)=(/0.0d0,1.0d0,0.0d0/)   !NORMAL Y+
N(5,:)=(/0.0d0,0.0d0,-1.0d0/)  !NORMAL Z-
N(6,:)=(/0.0d0,0.0d0,1.0d0/)   !NORMAL Z+

IF ((I>1) .AND. (I<NX) .AND. (J>1) .AND. (J<NY) .AND. (K>1) .AND. (K<NZ)) THEN
IF (BOUNDS_D(I,J,K)==0) THEN

!NEIGHBORS
RHO_V(1)=RHO_ANT_D(I-1,J,K)
 VX_V(1)=     VX_D(I-1,J,K)
 VY_V(1)=     VY_D(I-1,J,K)
 VZ_V(1)=     VZ_D(I-1,J,K)
ENE_V(1)=ENE_ANT_D(I-1,J,K)
PRE_V(1)=    PRE_D(I-1,J,K)
RVX_V(1)=RVX_ANT_D(I-1,J,K)
RVY_V(1)=RVY_ANT_D(I-1,J,K)
RVZ_V(1)=RVZ_ANT_D(I-1,J,K)

RHO_V(2)=RHO_ANT_D(I+1,J,K)
 VX_V(2)=     VX_D(I+1,J,K)
 VY_V(2)=     VY_D(I+1,J,K)
 VZ_V(2)=     VZ_D(I+1,J,K)
ENE_V(2)=ENE_ANT_D(I+1,J,K)
PRE_V(2)=    PRE_D(I+1,J,K)
RVX_V(2)=RVX_ANT_D(I+1,J,K)
RVY_V(2)=RVY_ANT_D(I+1,J,K)
RVZ_V(2)=RVZ_ANT_D(I+1,J,K)

RHO_V(3)=RHO_ANT_D(I,J-1,K)
 VX_V(3)=     VX_D(I,J-1,K)
 VY_V(3)=     VY_D(I,J-1,K)
 VZ_V(3)=     VZ_D(I,J-1,K)
ENE_V(3)=ENE_ANT_D(I,J-1,K)
PRE_V(3)=    PRE_D(I,J-1,K)
RVX_V(3)=RVX_ANT_D(I,J-1,K)
RVY_V(3)=RVY_ANT_D(I,J-1,K)
RVZ_V(3)=RVZ_ANT_D(I,J-1,K)

RHO_V(4)=RHO_ANT_D(I,J+1,K)
 VX_V(4)=     VX_D(I,J+1,K)
 VY_V(4)=     VY_D(I,J+1,K)
 VZ_V(4)=     VZ_D(I,J+1,K)
ENE_V(4)=ENE_ANT_D(I,J+1,K)
PRE_V(4)=    PRE_D(I,J+1,K)
RVX_V(4)=RVX_ANT_D(I,J+1,K)
RVY_V(4)=RVY_ANT_D(I,J+1,K)
RVZ_V(4)=RVZ_ANT_D(I,J+1,K)

RHO_V(5)=RHO_ANT_D(I,J,K-1)
 VX_V(5)=     VX_D(I,J,K-1)
 VY_V(5)=     VY_D(I,J,K-1)
 VZ_V(5)=     VZ_D(I,J,K-1)
ENE_V(5)=ENE_ANT_D(I,J,K-1)
PRE_V(5)=    PRE_D(I,J,K-1)
RVX_V(5)=RVX_ANT_D(I,J,K-1)
RVY_V(5)=RVY_ANT_D(I,J,K-1)
RVZ_V(5)=RVZ_ANT_D(I,J,K-1)

RHO_V(6)=RHO_ANT_D(I,J,K+1)
 VX_V(6)=     VX_D(I,J,K+1)
 VY_V(6)=     VY_D(I,J,K+1)
 VZ_V(6)=     VZ_D(I,J,K+1)
ENE_V(6)=ENE_ANT_D(I,J,K+1)
PRE_V(6)=    PRE_D(I,J,K+1)
RVX_V(6)=RVX_ANT_D(I,J,K+1)
RVY_V(6)=RVY_ANT_D(I,J,K+1)
RVZ_V(6)=RVZ_ANT_D(I,J,K+1)

IF(BOUNDS_D(I-1,J,K)==1) THEN !REFLECTIVE WALL RIGHT
RHO_V(1)=RHO_ANT_D(I,J,K)
RVX_V(1)=-RVX_ANT_D(I,J,K)
RVY_V(1)=RVY_ANT_D(I,J,K)
RVZ_V(1)=RVZ_ANT_D(I,J,K)
ENE_V(1)=ENE_ANT_D(I,J,K)
PRE_V(1)=PRE_D(I,J,K)

VX_V(1)=RVX_V(1)/RHO_V(1)
VY_V(1)=RVY_V(1)/RHO_V(1)
VZ_V(1)=RVZ_V(1)/RHO_V(1)
END IF

IF(BOUNDS_D(I+1,J,K)==1) THEN !REFLECTIVE WALL LEFT
RHO_V(2)=RHO_ANT_D(I,J,K)
RVX_V(2)=-RVX_ANT_D(I,J,K)
RVY_V(2)=RVY_ANT_D(I,J,K)
RVZ_V(2)=RVZ_ANT_D(I,J,K)
ENE_V(2)=ENE_ANT_D(I,J,K)
PRE_V(2)=PRE_D(I,J,K)

VX_V(2)=RVX_V(2)/RHO_V(2)
VY_V(2)=RVY_V(2)/RHO_V(2)
VZ_V(2)=RVZ_V(2)/RHO_V(2)
END IF

IF(BOUNDS_D(I,J,K-1)==1) THEN !REFLECTIVE FLOOR
RHO_V(5)=RHO_ANT_D(I,J,K)
RVX_V(5)=RVX_ANT_D(I,J,K)
RVY_V(5)=RVY_ANT_D(I,J,K)
RVZ_V(5)=-RVZ_ANT_D(I,J,K)
ENE_V(5)=ENE_ANT_D(I,J,K)
PRE_V(5)=PRE_D(I,J,K)

VX_V(5)=RVX_V(5)/RHO_V(5)
VY_V(5)=RVY_V(5)/RHO_V(5)
VZ_V(5)=RVZ_V(5)/RHO_V(5)
END IF

IF(BOUNDS_D(I,J,K+1)==1) THEN !REFLECTIVE CEIL
RHO_V(6)=RHO_ANT_D(I,J,K)
RVX_V(6)=RVX_ANT_D(I,J,K)
RVY_V(6)=RVY_ANT_D(I,J,K)
RVZ_V(6)=-RVZ_ANT_D(I,J,K)
ENE_V(6)=ENE_ANT_D(I,J,K)
PRE_V(6)=PRE_D(I,J,K)

VX_V(6)=RVX_V(6)/RHO_V(6)
VY_V(6)=RVY_V(6)/RHO_V(6)
VZ_V(6)=RVZ_V(6)/RHO_V(6)
END IF


!!!EQUATION 3 RVY
FUK=(/VX_D(I,J,K) , VY_D(I,J,K) , VZ_D(I,J,K)/)

!X+
U_PLUS=RVY_V(2)-(DIST_MAX/4.0d0)*SLOPES_D(I+1,J,K,1)
U_MINUS=RVY_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
FUL2=(/VX_V(2) , VY_V(2) , VZ_V(2)/)
P2=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL2(1))*(U_MINUS+U_PLUS)))*AREAS2

!X-
U_PLUS=RVY_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
U_MINUS=RVY_V(1)+(DIST_MAX/4.0d0)*SLOPES_D(I-1,J,K,1)
FUL1=(/VX_V(1) , VY_V(1) , VZ_V(1)/)
P1=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL1(1))*(U_MINUS+U_PLUS)))*AREAS1

!Y+
U_PLUS=RVY_V(4)-(DIST_MAX/4.0d0)*SLOPES_D(I,J+1,K,2)
U_MINUS=RVY_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
FUL4=(/VX_V(4) , VY_V(4) , VZ_V(4)/)
P4=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL4(2))*(U_MINUS+U_PLUS)) +0.5*(PRE_D(I,J,K)+PRE_V(4)))*AREAS4

!Y-
U_PLUS=RVY_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
U_MINUS=RVY_V(3)+(DIST_MAX/4.0d0)*SLOPES_D(I,J-1,K,2)
FUL3=(/VX_V(3) , VY_V(3) , VZ_V(3)/)
P3=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL3(2))*(U_MINUS+U_PLUS)) +0.5*(PRE_D(I,J,K)+PRE_V(3)))*AREAS3

!Z+
U_PLUS=RVY_V(6)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K+1,3)
U_MINUS=RVY_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
FUL6=(/VX_V(6) , VY_V(6) , VZ_V(6)/)
P6=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL6(3))*(U_MINUS+U_PLUS)))*AREAS6

!Z-
U_PLUS=RVY_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
U_MINUS=RVY_V(5)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K-1,3)
FUL5=(/VX_V(5) , VY_V(5) , VZ_V(5)/)
P5=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL5(3))*(U_MINUS+U_PLUS)))*AREAS5

RVY_D(I,J,K)=RVY_ANT_D(I,J,K)-(DELTA_T/VOLUMES)*(P1+P2+P3+P4+P5+P6)

END IF !BOUNDS

END IF
END SUBROUTINE SCHEME3

ATTRIBUTES(GLOBAL) SUBROUTINE SCHEME4(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE) 	  :: RHO_D(:,:,:),RVX_D(:,:,:),RVY_D(:,:,:),RVZ_D(:,:,:),ENE_D(:,:,:),PRE_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: VX_D(:,:,:),VY_D(:,:,:),VZ_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: RHO_ANT_D(:,:,:),RVX_ANT_D(:,:,:),RVY_ANT_D(:,:,:),RVZ_ANT_D(:,:,:),ENE_ANT_D(:,:,:)
REAL(KIND=C_DOUBLE),VALUE :: DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6,DIST_MAX
INTEGER(KIND=C_INT) 	  :: BOUNDS_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: SLOPES_D(:,:,:,:)
!LOCAL VARIABLES
INTEGER(KIND=C_INT) 	          :: I,J,K,L
REAL(KIND=C_DOUBLE),DIMENSION(6)  :: RHO_V,RVX_V,RVY_V,RVZ_V,VX_V,VY_V,VZ_V,ENE_V,PRE_V
REAL(KIND=C_DOUBLE),DIMENSION(6,3):: N
REAL(KIND=C_DOUBLE)				  :: P1,P2,P3,P4,P5,P6,U_PLUS,U_MINUS,XI
REAL(KIND=C_DOUBLE),DIMENSION(3)  :: FUK,FUL1,FUL2,FUL3,FUL4,FUL5,FUL6,BUK,BUL1,BUL2,BUL3,BUL4,BUL5,BUL6

XI=2.0d0

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

!FACE SURFACE NORMALS
N(1,:)=(/-1.0d0,0.0d0,0.0d0/)  !NORMAL X-
N(2,:)=(/1.0d0,0.d0,0.0d0/)    !NORMAL X+
N(3,:)=(/0.0d0,-1.0d0,0.0d0/)  !NORMAL Y-
N(4,:)=(/0.0d0,1.0d0,0.0d0/)   !NORMAL Y+
N(5,:)=(/0.0d0,0.0d0,-1.0d0/)  !NORMAL Z-
N(6,:)=(/0.0d0,0.0d0,1.0d0/)   !NORMAL Z+

IF ((I>1) .AND. (I<NX) .AND. (J>1) .AND. (J<NY) .AND. (K>1) .AND. (K<NZ)) THEN
IF (BOUNDS_D(I,J,K)==0) THEN

!NEIGHBORS
RHO_V(1)=RHO_ANT_D(I-1,J,K)
 VX_V(1)=     VX_D(I-1,J,K)
 VY_V(1)=     VY_D(I-1,J,K)
 VZ_V(1)=     VZ_D(I-1,J,K)
ENE_V(1)=ENE_ANT_D(I-1,J,K)
PRE_V(1)=    PRE_D(I-1,J,K)
RVX_V(1)=RVX_ANT_D(I-1,J,K)
RVY_V(1)=RVY_ANT_D(I-1,J,K)
RVZ_V(1)=RVZ_ANT_D(I-1,J,K)

RHO_V(2)=RHO_ANT_D(I+1,J,K)
 VX_V(2)=     VX_D(I+1,J,K)
 VY_V(2)=     VY_D(I+1,J,K)
 VZ_V(2)=     VZ_D(I+1,J,K)
ENE_V(2)=ENE_ANT_D(I+1,J,K)
PRE_V(2)=    PRE_D(I+1,J,K)
RVX_V(2)=RVX_ANT_D(I+1,J,K)
RVY_V(2)=RVY_ANT_D(I+1,J,K)
RVZ_V(2)=RVZ_ANT_D(I+1,J,K)

RHO_V(3)=RHO_ANT_D(I,J-1,K)
 VX_V(3)=     VX_D(I,J-1,K)
 VY_V(3)=     VY_D(I,J-1,K)
 VZ_V(3)=     VZ_D(I,J-1,K)
ENE_V(3)=ENE_ANT_D(I,J-1,K)
PRE_V(3)=    PRE_D(I,J-1,K)
RVX_V(3)=RVX_ANT_D(I,J-1,K)
RVY_V(3)=RVY_ANT_D(I,J-1,K)
RVZ_V(3)=RVZ_ANT_D(I,J-1,K)

RHO_V(4)=RHO_ANT_D(I,J+1,K)
 VX_V(4)=     VX_D(I,J+1,K)
 VY_V(4)=     VY_D(I,J+1,K)
 VZ_V(4)=     VZ_D(I,J+1,K)
ENE_V(4)=ENE_ANT_D(I,J+1,K)
PRE_V(4)=    PRE_D(I,J+1,K)
RVX_V(4)=RVX_ANT_D(I,J+1,K)
RVY_V(4)=RVY_ANT_D(I,J+1,K)
RVZ_V(4)=RVZ_ANT_D(I,J+1,K)

RHO_V(5)=RHO_ANT_D(I,J,K-1)
 VX_V(5)=     VX_D(I,J,K-1)
 VY_V(5)=     VY_D(I,J,K-1)
 VZ_V(5)=     VZ_D(I,J,K-1)
ENE_V(5)=ENE_ANT_D(I,J,K-1)
PRE_V(5)=    PRE_D(I,J,K-1)
RVX_V(5)=RVX_ANT_D(I,J,K-1)
RVY_V(5)=RVY_ANT_D(I,J,K-1)
RVZ_V(5)=RVZ_ANT_D(I,J,K-1)

RHO_V(6)=RHO_ANT_D(I,J,K+1)
 VX_V(6)=     VX_D(I,J,K+1)
 VY_V(6)=     VY_D(I,J,K+1)
 VZ_V(6)=     VZ_D(I,J,K+1)
ENE_V(6)=ENE_ANT_D(I,J,K+1)
PRE_V(6)=    PRE_D(I,J,K+1)
RVX_V(6)=RVX_ANT_D(I,J,K+1)
RVY_V(6)=RVY_ANT_D(I,J,K+1)
RVZ_V(6)=RVZ_ANT_D(I,J,K+1)

IF(BOUNDS_D(I-1,J,K)==1) THEN !REFLECTIVE WALL RIGHT
RHO_V(1)=RHO_ANT_D(I,J,K)
RVX_V(1)=-RVX_ANT_D(I,J,K)
RVY_V(1)=RVY_ANT_D(I,J,K)
RVZ_V(1)=RVZ_ANT_D(I,J,K)
ENE_V(1)=ENE_ANT_D(I,J,K)
PRE_V(1)=PRE_D(I,J,K)

VX_V(1)=RVX_V(1)/RHO_V(1)
VY_V(1)=RVY_V(1)/RHO_V(1)
VZ_V(1)=RVZ_V(1)/RHO_V(1)
END IF

IF(BOUNDS_D(I+1,J,K)==1) THEN !REFLECTIVE WALL LEFT
RHO_V(2)=RHO_ANT_D(I,J,K)
RVX_V(2)=-RVX_ANT_D(I,J,K)
RVY_V(2)=RVY_ANT_D(I,J,K)
RVZ_V(2)=RVZ_ANT_D(I,J,K)
ENE_V(2)=ENE_ANT_D(I,J,K)
PRE_V(2)=PRE_D(I,J,K)

VX_V(2)=RVX_V(2)/RHO_V(2)
VY_V(2)=RVY_V(2)/RHO_V(2)
VZ_V(2)=RVZ_V(2)/RHO_V(2)
END IF

IF(BOUNDS_D(I,J,K-1)==1) THEN !REFLECTIVE FLOOR
RHO_V(5)=RHO_ANT_D(I,J,K)
RVX_V(5)=RVX_ANT_D(I,J,K)
RVY_V(5)=RVY_ANT_D(I,J,K)
RVZ_V(5)=-RVZ_ANT_D(I,J,K)
ENE_V(5)=ENE_ANT_D(I,J,K)
PRE_V(5)=PRE_D(I,J,K)

VX_V(5)=RVX_V(5)/RHO_V(5)
VY_V(5)=RVY_V(5)/RHO_V(5)
VZ_V(5)=RVZ_V(5)/RHO_V(5)
END IF

IF(BOUNDS_D(I,J,K+1)==1) THEN !REFLECTIVE CEIL
RHO_V(6)=RHO_ANT_D(I,J,K)
RVX_V(6)=RVX_ANT_D(I,J,K)
RVY_V(6)=RVY_ANT_D(I,J,K)
RVZ_V(6)=-RVZ_ANT_D(I,J,K)
ENE_V(6)=ENE_ANT_D(I,J,K)
PRE_V(6)=PRE_D(I,J,K)

VX_V(6)=RVX_V(6)/RHO_V(6)
VY_V(6)=RVY_V(6)/RHO_V(6)
VZ_V(6)=RVZ_V(6)/RHO_V(6)
END IF


!!!EQUATION 4 RVZ
FUK=(/VX_D(I,J,K) , VY_D(I,J,K) , VZ_D(I,J,K)/)

!X+
U_PLUS=RVZ_V(2)-(DIST_MAX/4.0d0)*SLOPES_D(I+1,J,K,1)
U_MINUS=RVZ_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
FUL2=(/VX_V(2) , VY_V(2) , VZ_V(2)/)
P2=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL2(1))*(U_MINUS+U_PLUS)))*AREAS2

!X-
U_PLUS=RVZ_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
U_MINUS=RVZ_V(1)+(DIST_MAX/4.0d0)*SLOPES_D(I-1,J,K,1)
FUL1=(/VX_V(1) , VY_V(1) , VZ_V(1)/)
P1=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL1(1))*(U_MINUS+U_PLUS)))*AREAS1

!Y+
U_PLUS=RVZ_V(4)-(DIST_MAX/4.0d0)*SLOPES_D(I,J+1,K,2)
U_MINUS=RVZ_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
FUL4=(/VX_V(4) , VY_V(4) , VZ_V(4)/)
P4=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL4(2))*(U_MINUS+U_PLUS)))*AREAS4

!Y-
U_PLUS=RVZ_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
U_MINUS=RVZ_V(3)+(DIST_MAX/4.0d0)*SLOPES_D(I,J-1,K,2)
FUL3=(/VX_V(3) , VY_V(3) , VZ_V(3)/)
P3=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL3(2))*(U_MINUS+U_PLUS)))*AREAS3

!Z+
U_PLUS=RVZ_V(6)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K+1,3)
U_MINUS=RVZ_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
FUL6=(/VX_V(6) , VY_V(6) , VZ_V(6)/)
P6=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL6(3))*(U_MINUS+U_PLUS)) +0.5*(PRE_D(I,J,K)+PRE_V(6)))*AREAS6

!Z-
U_PLUS=RVZ_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
U_MINUS=RVZ_V(5)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K-1,3)
FUL5=(/VX_V(5) , VY_V(5) , VZ_V(5)/)
P5=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL5(3))*(U_MINUS+U_PLUS)) +0.5*(PRE_D(I,J,K)+PRE_V(5)))*AREAS5

RVZ_D(I,J,K)=RVZ_ANT_D(I,J,K)-(DELTA_T/VOLUMES)*(P1+P2+P3+P4+P5+P6)

END IF !BOUNDS

END IF
END SUBROUTINE SCHEME4

ATTRIBUTES(GLOBAL) SUBROUTINE SCHEME5(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,PRE_D,VX_D,VY_D,VZ_D,BOUNDS_D,SLOPES_D,DIST_MAX,&
RHO_ANT_D,RVX_ANT_D,RVY_ANT_D,RVZ_ANT_D,ENE_ANT_D,NX,NY,NZ,DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE) 	  :: RHO_D(:,:,:),RVX_D(:,:,:),RVY_D(:,:,:),RVZ_D(:,:,:),ENE_D(:,:,:),PRE_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: VX_D(:,:,:),VY_D(:,:,:),VZ_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: RHO_ANT_D(:,:,:),RVX_ANT_D(:,:,:),RVY_ANT_D(:,:,:),RVZ_ANT_D(:,:,:),ENE_ANT_D(:,:,:)
REAL(KIND=C_DOUBLE),VALUE :: DELTA_T,VOLUMES,SUP,AREAS1,AREAS2,AREAS3,AREAS4,AREAS5,AREAS6,DIST_MAX
INTEGER(KIND=C_INT) 	  :: BOUNDS_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: SLOPES_D(:,:,:,:)
!LOCAL VARIABLES
INTEGER(KIND=C_INT) 	          :: I,J,K,L
REAL(KIND=C_DOUBLE),DIMENSION(6)  :: RHO_V,RVX_V,RVY_V,RVZ_V,VX_V,VY_V,VZ_V,ENE_V,PRE_V
REAL(KIND=C_DOUBLE),DIMENSION(6,3):: N
REAL(KIND=C_DOUBLE)				  :: P1,P2,P3,P4,P5,P6,U_MINUS,U_PLUS,XI
REAL(KIND=C_DOUBLE),DIMENSION(3)  :: FUK,FUL1,FUL2,FUL3,FUL4,FUL5,FUL6,BUK,BUL1,BUL2,BUL3,BUL4,BUL5,BUL6

XI=2.0d0

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

!FACE SURFACE NORMALS
N(1,:)=(/-1.0d0,0.0d0,0.0d0/)  !NORMAL X-
N(2,:)=(/1.0d0,0.d0,0.0d0/)    !NORMAL X+
N(3,:)=(/0.0d0,-1.0d0,0.0d0/)  !NORMAL Y-
N(4,:)=(/0.0d0,1.0d0,0.0d0/)   !NORMAL Y+
N(5,:)=(/0.0d0,0.0d0,-1.0d0/)  !NORMAL Z-
N(6,:)=(/0.0d0,0.0d0,1.0d0/)   !NORMAL Z+

IF ((I>1) .AND. (I<NX) .AND. (J>1) .AND. (J<NY) .AND. (K>1) .AND. (K<NZ)) THEN
IF (BOUNDS_D(I,J,K)==0) THEN

!NEIGHBORS
RHO_V(1)=RHO_ANT_D(I-1,J,K)
 VX_V(1)=     VX_D(I-1,J,K)
 VY_V(1)=     VY_D(I-1,J,K)
 VZ_V(1)=     VZ_D(I-1,J,K)
ENE_V(1)=ENE_ANT_D(I-1,J,K)
PRE_V(1)=    PRE_D(I-1,J,K)
RVX_V(1)=RVX_ANT_D(I-1,J,K)
RVY_V(1)=RVY_ANT_D(I-1,J,K)
RVZ_V(1)=RVZ_ANT_D(I-1,J,K)

RHO_V(2)=RHO_ANT_D(I+1,J,K)
 VX_V(2)=     VX_D(I+1,J,K)
 VY_V(2)=     VY_D(I+1,J,K)
 VZ_V(2)=     VZ_D(I+1,J,K)
ENE_V(2)=ENE_ANT_D(I+1,J,K)
PRE_V(2)=    PRE_D(I+1,J,K)
RVX_V(2)=RVX_ANT_D(I+1,J,K)
RVY_V(2)=RVY_ANT_D(I+1,J,K)
RVZ_V(2)=RVZ_ANT_D(I+1,J,K)

RHO_V(3)=RHO_ANT_D(I,J-1,K)
 VX_V(3)=     VX_D(I,J-1,K)
 VY_V(3)=     VY_D(I,J-1,K)
 VZ_V(3)=     VZ_D(I,J-1,K)
ENE_V(3)=ENE_ANT_D(I,J-1,K)
PRE_V(3)=    PRE_D(I,J-1,K)
RVX_V(3)=RVX_ANT_D(I,J-1,K)
RVY_V(3)=RVY_ANT_D(I,J-1,K)
RVZ_V(3)=RVZ_ANT_D(I,J-1,K)

RHO_V(4)=RHO_ANT_D(I,J+1,K)
 VX_V(4)=     VX_D(I,J+1,K)
 VY_V(4)=     VY_D(I,J+1,K)
 VZ_V(4)=     VZ_D(I,J+1,K)
ENE_V(4)=ENE_ANT_D(I,J+1,K)
PRE_V(4)=    PRE_D(I,J+1,K)
RVX_V(4)=RVX_ANT_D(I,J+1,K)
RVY_V(4)=RVY_ANT_D(I,J+1,K)
RVZ_V(4)=RVZ_ANT_D(I,J+1,K)

RHO_V(5)=RHO_ANT_D(I,J,K-1)
 VX_V(5)=     VX_D(I,J,K-1)
 VY_V(5)=     VY_D(I,J,K-1)
 VZ_V(5)=     VZ_D(I,J,K-1)
ENE_V(5)=ENE_ANT_D(I,J,K-1)
PRE_V(5)=    PRE_D(I,J,K-1)
RVX_V(5)=RVX_ANT_D(I,J,K-1)
RVY_V(5)=RVY_ANT_D(I,J,K-1)
RVZ_V(5)=RVZ_ANT_D(I,J,K-1)

RHO_V(6)=RHO_ANT_D(I,J,K+1)
 VX_V(6)=     VX_D(I,J,K+1)
 VY_V(6)=     VY_D(I,J,K+1)
 VZ_V(6)=     VZ_D(I,J,K+1)
ENE_V(6)=ENE_ANT_D(I,J,K+1)
PRE_V(6)=    PRE_D(I,J,K+1)
RVX_V(6)=RVX_ANT_D(I,J,K+1)
RVY_V(6)=RVY_ANT_D(I,J,K+1)
RVZ_V(6)=RVZ_ANT_D(I,J,K+1)

IF(BOUNDS_D(I-1,J,K)==1) THEN !REFLECTIVE WALL RIGHT
RHO_V(1)=RHO_ANT_D(I,J,K)
RVX_V(1)=-RVX_ANT_D(I,J,K)
RVY_V(1)=RVY_ANT_D(I,J,K)
RVZ_V(1)=RVZ_ANT_D(I,J,K)
ENE_V(1)=ENE_ANT_D(I,J,K)
PRE_V(1)=PRE_D(I,J,K)

VX_V(1)=RVX_V(1)/RHO_V(1)
VY_V(1)=RVY_V(1)/RHO_V(1)
VZ_V(1)=RVZ_V(1)/RHO_V(1)
END IF

IF(BOUNDS_D(I+1,J,K)==1) THEN !REFLECTIVE WALL LEFT
RHO_V(2)=RHO_ANT_D(I,J,K)
RVX_V(2)=-RVX_ANT_D(I,J,K)
RVY_V(2)=RVY_ANT_D(I,J,K)
RVZ_V(2)=RVZ_ANT_D(I,J,K)
ENE_V(2)=ENE_ANT_D(I,J,K)
PRE_V(2)=PRE_D(I,J,K)

VX_V(2)=RVX_V(2)/RHO_V(2)
VY_V(2)=RVY_V(2)/RHO_V(2)
VZ_V(2)=RVZ_V(2)/RHO_V(2)
END IF

IF(BOUNDS_D(I,J,K-1)==1) THEN !REFLECTIVE FLOOR
RHO_V(5)=RHO_ANT_D(I,J,K)
RVX_V(5)=RVX_ANT_D(I,J,K)
RVY_V(5)=RVY_ANT_D(I,J,K)
RVZ_V(5)=-RVZ_ANT_D(I,J,K)
ENE_V(5)=ENE_ANT_D(I,J,K)
PRE_V(5)=PRE_D(I,J,K)

VX_V(5)=RVX_V(5)/RHO_V(5)
VY_V(5)=RVY_V(5)/RHO_V(5)
VZ_V(5)=RVZ_V(5)/RHO_V(5)
END IF

IF(BOUNDS_D(I,J,K+1)==1) THEN !REFLECTIVE CEIL
RHO_V(6)=RHO_ANT_D(I,J,K)
RVX_V(6)=RVX_ANT_D(I,J,K)
RVY_V(6)=RVY_ANT_D(I,J,K)
RVZ_V(6)=-RVZ_ANT_D(I,J,K)
ENE_V(6)=ENE_ANT_D(I,J,K)
PRE_V(6)=PRE_D(I,J,K)

VX_V(6)=RVX_V(6)/RHO_V(6)
VY_V(6)=RVY_V(6)/RHO_V(6)
VZ_V(6)=RVZ_V(6)/RHO_V(6)
END IF



!!!EQUATION 5 ENE
FUK=(/VX_D(I,J,K) , VY_D(I,J,K) , VZ_D(I,J,K)/)

!X+
U_PLUS=ENE_V(2)-(DIST_MAX/4.0d0)*SLOPES_D(I+1,J,K,1)
U_MINUS=ENE_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
FUL2=(/VX_V(2) , VY_V(2) , VZ_V(2)/)
P2=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL2(1))*(U_MINUS+U_PLUS)) +0.5*(VX_D(I,J,K)*PRE_D(I,J,K)+VX_V(2)*PRE_V(2)))*AREAS2

!X-
U_PLUS=ENE_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,1)
U_MINUS=ENE_V(1)+(DIST_MAX/4.0d0)*SLOPES_D(I-1,J,K,1)
FUL1=(/VX_V(1) , VY_V(1) , VZ_V(1)/)
P1=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(1)+FUL1(1))*(U_MINUS+U_PLUS)) +0.5*(VX_D(I,J,K)*PRE_D(I,J,K)+VX_V(1)*PRE_V(1)))*AREAS1

!Y+
U_PLUS=ENE_V(4)-(DIST_MAX/4.0d0)*SLOPES_D(I,J+1,K,2)
U_MINUS=ENE_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
FUL4=(/VX_V(4) , VY_V(4) , VZ_V(4)/)
P4=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL4(2))*(U_MINUS+U_PLUS)) +0.5*(VY_D(I,J,K)*PRE_D(I,J,K)+VY_V(4)*PRE_V(4)))*AREAS4

!Y-
U_PLUS=ENE_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,2)
U_MINUS=ENE_V(3)+(DIST_MAX/4.0d0)*SLOPES_D(I,J-1,K,2)
FUL3=(/VX_V(3) , VY_V(3) , VZ_V(3)/)
P3=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(2)+FUL3(2))*(U_MINUS+U_PLUS)) +0.5*(VY_D(I,J,K)*PRE_D(I,J,K)+VY_V(3)*PRE_V(3)))*AREAS3

!Z+
U_PLUS=ENE_V(6)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K+1,3)
U_MINUS=ENE_ANT_D(I,J,K)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
FUL6=(/VX_V(6) , VY_V(6) , VZ_V(6)/)
P6=+(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL6(3))*(U_MINUS+U_PLUS)) +0.5*(VZ_D(I,J,K)*PRE_D(I,J,K)+VZ_V(6)*PRE_V(6)))*AREAS6

!Z-
U_PLUS=ENE_ANT_D(I,J,K)-(DIST_MAX/4.0d0)*SLOPES_D(I,J,K,3)
U_MINUS=ENE_V(5)+(DIST_MAX/4.0d0)*SLOPES_D(I,J,K-1,3)
FUL5=(/VX_V(5) , VY_V(5) , VZ_V(5)/)
P5=-(0.25*(XI*2.0d0*SUP*(U_MINUS-U_PLUS)+(FUK(3)+FUL5(3))*(U_MINUS+U_PLUS)) +0.5*(VZ_D(I,J,K)*PRE_D(I,J,K)+VZ_V(5)*PRE_V(5)))*AREAS5

ENE_D(I,J,K)=ENE_ANT_D(I,J,K)-(DELTA_T/VOLUMES)*(P1+P2+P3+P4+P5+P6)

END IF !BOUNDS

END IF
END SUBROUTINE SCHEME5


ATTRIBUTES(GLOBAL) SUBROUTINE PRESSURE(RHO_D,RVX_D,RVY_D,RVZ_D,VX_D,VY_D,VZ_D,BOUNDS_D,NX,NY,NZ,PRE_D,ENE_D)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE) 	  :: RHO_D(:,:,:),RVX_D(:,:,:),RVY_D(:,:,:),RVZ_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: VX_D(:,:,:),VY_D(:,:,:),VZ_D(:,:,:),PRE_D(:,:,:),ENE_D(:,:,:)
INTEGER(KIND=C_INT) 	  :: BOUNDS_D(:,:,:)
INTEGER(KIND=C_INT) 	  :: I,J,K

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

IF ((I<=NX) .AND. (J<=NY) .AND. (K<=NZ)) THEN
IF(BOUNDS_D(I,J,K)==0) THEN
VX_D(I,J,K)=RVX_D(I,J,K)/RHO_D(I,J,K)
VY_D(I,J,K)=RVY_D(I,J,K)/RHO_D(I,J,K)
VZ_D(I,J,K)=RVZ_D(I,J,K)/RHO_D(I,J,K)
PRE_D(I,J,K)=0.4d0*(ENE_D(I,J,K)-0.5d0*RHO_D(I,J,K)*(VX_D(I,J,K)**2.0d0+VY_D(I,J,K)**2.0d0+VZ_D(I,J,K)**2.0d0))
END IF
END IF

END SUBROUTINE PRESSURE

ATTRIBUTES(GLOBAL) SUBROUTINE RKCONSOLIDATE(RHO_D,RVX_D,RVY_D,RVZ_D,ENE_D,&
RHO_ANT2_D,RVX_ANT2_D,RVY_ANT2_D,RVZ_ANT2_D,ENE_ANT2_D,BOUNDS_D,NX,NY,NZ)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE) 	  :: RHO_D(:,:,:),RVX_D(:,:,:),RVY_D(:,:,:),RVZ_D(:,:,:),ENE_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: RHO_ANT2_D(:,:,:),RVX_ANT2_D(:,:,:),RVY_ANT2_D(:,:,:),RVZ_ANT2_D(:,:,:),ENE_ANT2_D(:,:,:)
INTEGER(KIND=C_INT) 	  :: BOUNDS_D(:,:,:)
INTEGER(KIND=C_INT) 	  :: I,J,K

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

IF ((I<=NX) .AND. (J<=NY) .AND. (K<=NZ)) THEN
IF(BOUNDS_D(I,J,K)==0) THEN
RHO_D(I,J,K)=0.5d0*(RHO_ANT2_D(I,J,K)+RHO_D(I,J,K))
RVX_D(I,J,K)=0.5d0*(RVX_ANT2_D(I,J,K)+RVX_D(I,J,K))
RVY_D(I,J,K)=0.5d0*(RVY_ANT2_D(I,J,K)+RVY_D(I,J,K))
RVZ_D(I,J,K)=0.5d0*(RVZ_ANT2_D(I,J,K)+RVZ_D(I,J,K))
ENE_D(I,J,K)=0.5d0*(ENE_ANT2_D(I,J,K)+ENE_D(I,J,K))
END IF
END IF

END SUBROUTINE RKCONSOLIDATE

ATTRIBUTES(GLOBAL) SUBROUTINE SLOPELIMITER(U_D,SLOPES_D,BOUNDS_D,NX,NY,NZ,DIST_MAX,ALFA,TETA,INVERSOR_X,INVERSOR_Z)
USE ISO_C_BINDING
IMPLICIT NONE
INTEGER(KIND=C_INT),VALUE :: NX,NY,NZ
REAL(KIND=C_DOUBLE),VALUE :: ALFA,TETA,INVERSOR_X,INVERSOR_Z,DIST_MAX
REAL(KIND=C_DOUBLE) 	  :: U_D(:,:,:)
REAL(KIND=C_DOUBLE) 	  :: SLOPES_D(:,:,:,:)
INTEGER(KIND=C_INT) 	  :: BOUNDS_D(:,:,:)
INTEGER(KIND=C_INT) 	  :: I,J,K
REAL(KIND=C_DOUBLE)				 :: U,PHI1,PHI2,PHI3,MM
REAL(KIND=C_DOUBLE),DIMENSION(6) :: V
!USE INVERSOR=1.0d0 IF DENSITY OR PRESSURE, INVERSOR=-1.0d0 IF MOMENTUM 

!RECOVERS INDEXES
I= BLOCKDIM%X * (BLOCKIDX%X - 1) + THREADIDX%X
J= BLOCKDIM%Y * (BLOCKIDX%Y - 1) + THREADIDX%Y
K= BLOCKDIM%Z * (BLOCKIDX%Z - 1) + THREADIDX%Z

IF ((I>1) .AND. (I<NX) .AND. (J>1) .AND. (J<NY) .AND. (K>1) .AND. (K<NZ)) THEN
IF(BOUNDS_D(I,J,K)==0) THEN
U=U_D(I,J,K)
!NEIGHBORS
V(1)=U_D(I-1,J,K)
V(2)=U_D(I+1,J,K)
V(3)=U_D(I,J-1,K)
V(4)=U_D(I,J+1,K)
V(5)=U_D(I,J,K-1)
V(6)=U_D(I,J,K+1)

IF(BOUNDS_D(I-1,J,K)==1) THEN !REFLECTIVE WALL LEFT
V(1)=INVERSOR_X*U_D(I,J,K)
END IF

IF(BOUNDS_D(I+1,J,K)==1) THEN !REFLECTIVE WALL RIGHT
V(2)=INVERSOR_X*U_D(I,J,K)
END IF

IF(BOUNDS_D(I,J,K-1)==1) THEN !REFLECTIVE FLOOR
V(5)=INVERSOR_Z*U_D(I,J,K)
END IF

IF(BOUNDS_D(I,J,K+1)==1) THEN !REFLECTIVE CEIL
V(6)=INVERSOR_Z*U_D(I,J,K)
END IF

!MM2
!X
PHI1=ALFA*TETA*(U-V(1))/DIST_MAX
PHI2=ALFA*(V(2)-V(1))/(2.0d0*DIST_MAX)
PHI3=ALFA*TETA*(V(2)-U)/DIST_MAX


MM=0.5d0*(SIGN(1.d0,PHI1)+SIGN(1.d0,PHI2))*MIN(ABS(PHI1),ABS(PHI2))
SLOPES_D(I,J,K,1)=0.5d0*(SIGN(1.d0,MM)+SIGN(1.d0,PHI3))*MIN(ABS(MM),ABS(PHI3))

!Y
PHI1=ALFA*TETA*(U-V(3))/DIST_MAX
PHI2=ALFA*(V(4)-V(3))/(2.0d0*DIST_MAX)
PHI3=ALFA*TETA*(V(4)-U)/DIST_MAX


MM=0.5d0*(SIGN(1.d0,PHI1)+SIGN(1.d0,PHI2))*MIN(ABS(PHI1),ABS(PHI2))
SLOPES_D(I,J,K,2)=0.5d0*(SIGN(1.d0,MM)+SIGN(1.d0,PHI3))*MIN(ABS(MM),ABS(PHI3))

!Z
PHI1=ALFA*TETA*(U-V(5))/DIST_MAX
PHI2=ALFA*(V(6)-V(5))/(2.0d0*DIST_MAX)
PHI3=ALFA*TETA*(V(6)-U)/DIST_MAX


MM=0.5d0*(SIGN(1.d0,PHI1)+SIGN(1.d0,PHI2))*MIN(ABS(PHI1),ABS(PHI2))
SLOPES_D(I,J,K,3)=0.5d0*(SIGN(1.d0,MM)+SIGN(1.d0,PHI3))*MIN(ABS(MM),ABS(PHI3))


END IF
END IF

END SUBROUTINE SLOPELIMITER

END MODULE