!LAGRANGIAN-EULERIAN 3D EULER EQUATIONS FORWARD STEP PROBLEM CUDA (PEDRO GODOI 2025)
!MAIN PROGRAM
PROGRAM PRINCIPAL

USE CUDAFOR
USE ISO_C_BINDING

!IMPLICIT NONE
!PARAMETERS.DAT VARIABLES
REAL(KIND=C_DOUBLE)               ::CFL_BASE,X0,XF,Y0,YF,Z0,ZF,T0,TF
REAL(KIND=C_DOUBLE),DIMENSION(3)  ::FLUX_DATA
INTEGER(KIND=C_INT)               ::NX,NY,NZ,MESH_TYPE,BORDER_TYPE,CI_TYPE,FLUX_TYPE,DISC_TYPE,MS_TYPE
INTEGER(KIND=C_INT)				  ::SAVE_CI,SAVE_E,SAVE_FINAL,SAVE_TYPE,ANIMA_FRAME,MPI_NX,MPI_NY,MPI_NZ

!GENERAL PURPOSE VARIABLES
REAL(KIND=C_DOUBLE)									::TCPU1,TCPU2,TCPU_START,TCPU_FINISH,VOLUMES,DIST_MAX,PI
REAL(KIND=C_DOUBLE)									::DIVB,DUMMY1
REAL(KIND=C_DOUBLE),DIMENSION(:),ALLOCATABLE	    ::FACE_AREAS,I_LOCAL,J_LOCAL,K_LOCAL
REAL(KIND=C_DOUBLE),DIMENSION(:,:),ALLOCATABLE	    ::FACE_AREAS_TET
REAL(KIND=C_DOUBLE),DIMENSION(:,:,:),ALLOCATABLE    ::RHO,VX,VY,VZ,ENE,PRE
REAL(KIND=C_DOUBLE),DIMENSION(:,:,:),ALLOCATABLE    ::NORMALS
REAL(KIND=C_DOUBLE),DIMENSION(:,:,:,:),ALLOCATABLE  ::CENTERS
REAL(KIND=C_DOUBLE),DIMENSION(:,:,:,:),ALLOCATABLE  ::RHO_T,VX_T,VY_T,VZ_T,ENE_T,PRE_T
REAL(KIND=C_DOUBLE),DIMENSION(:,:,:,:,:),ALLOCATABLE::CENTERS_TET
INTEGER(KIND=C_INT)                                 ::MANIPULA,NUMEL_MESH,I,NX_LOCAL,NY_LOCAL,NZ_LOCAL
INTEGER(KIND=C_INT),DIMENSION(:,:),ALLOCATABLE		::BLOCK_ADRESS
INTEGER(KIND=C_INT),DIMENSION(:,:,:),ALLOCATABLE	::BLOCK_ID,BOUNDS
CHARACTER(KIND=C_CHAR,LEN=4)               			::MPI_ID_STR

!CUDA VARIABLES
INTEGER(KIND=C_INT)	:: ISTAT,NUM_DEV
TYPE(CUDADEVICEPROP):: PROP_DEV

ISTAT=CUDAGETDEVICECOUNT(NUM_DEV)
ISTAT=CUDAGETDEVICEPROPERTIES(PROP_DEV,0)
PRINT*,'NUMBER OF DEVICES=',NUM_DEV
ISTAT=CUDASETDEVICE(0)
PRINT*,'DEVICE 0 SET TO HOST'


!!!START TIME COUNTING
CALL CPU_TIME(TCPU_START)

!!!PI
PI = 4*ATAN(1.d0)

!!!FOLDERS AND FILES MANIPULATION (MAIN PROCESS ONLY)
MANIPULA = SYSTEM('if test -e OUTPUT; then rm -r OUTPUT; fi;') !REMOVE OUTPUT FOLDER (IF EXISTS)
MANIPULA = SYSTEM('mkdir OUTPUT')                              !CREATE OUTPUT FOLDER
MANIPULA = SYSTEM('mkdir OUTPUT/ANIMA')                        !CREATE ANIMA FOLDER (FOR ANIMATIONS)
MANIPULA = SYSTEM('mkdir OUTPUT/FINAL')                        !CREATE FINAL FOLDER (FOR FINAL RESULT)
MANIPULA = SYSTEM('mkdir OUTPUT/BACKUP')                       !CREATE FINAL FOLDER (FOR FINAL RESULT)
MANIPULA = SYSTEM('cp '//'PARAMETERS.DAT'//' OUTPUT')          !COPY PARAMETERS FILE TO OUTPUT

!!!OPEN LOG FILE
OPEN(99,FILE='OUTPUT/LOGS.CSV',STATUS='NEW')
WRITE(99,'(A17,A6,I0.3,A6)') 'PROGRAM VERSION, ','EE-CUD',4,'LINREC'


!!!DATA READING
CALL CPU_TIME(TCPU1)
OPEN(1,FILE='PARAMETERS.DAT',STATUS='OLD')

READ(1,*) !-----PARAMETERS LE3D-----
READ(1,*) !---MESH
READ(1,*) X0,XF,Y0,YF,Z0,ZF
READ(1,*) NX,NY,NZ
READ(1,*) T0,TF
READ(1,*) MESH_TYPE
READ(1,*) BORDER_TYPE
READ(1,*) !---METHOD
READ(1,*) CFL_BASE
READ(1,*) DISC_TYPE
READ(1,*) !---INITIAL CONDITION
READ(1,*) CI_TYPE
READ(1,*) MS_TYPE
READ(1,*) !---FLUX
READ(1,*) FLUX_TYPE
READ(1,*) FLUX_DATA
READ(1,*) !---OUTPUT
READ(1,*) SAVE_CI
READ(1,*) SAVE_E
READ(1,*) SAVE_FINAL
READ(1,*) ANIMA_FRAME
READ(1,*) SAVE_TYPE

CLOSE(1)
CALL CPU_TIME(TCPU2)
WRITE(99,'(A18,E20.12)') 'DATA READING TIME,',TCPU2-TCPU1 !(MAIN PROCESS ONLY)


!!!ADJUST DOMAIN
! XF=XF*PI
! YF=YF*PI
! ZF=ZF*PI

!!!MAIN PROGRAM
SELECT CASE(MESH_TYPE)
!!!!!!!!!!!!!!!!!!!!!!!!!!CUBES MESH!!!!!!!!!!!!!!!!!!!!!!!!!!
CASE(0)
!! CREATE MESH
NUMEL_MESH=NX*NY*NZ                  		 !NUMBER OF ELEMENTS IN THE MESH
ALLOCATE(CENTERS(NX+2,NY+2,NZ+2,3))          !COORDINATES OF ELEMENT CENTERS [X Y Z]
ALLOCATE(FACE_AREAS(6))              		 !AREA OF EACH ELEMENT FACE [X- X+ Y- Y+ Z- Z+] 

ALLOCATE(BOUNDS(NX+2,NY+2,NZ+2))             !TYPE OF CELL [0=COMMON , 1=WALL]

CALL CPU_TIME(TCPU1)
CALL MESH_CUBE(X0,XF,Y0,YF,Z0,ZF,NX+2,NY+2,NZ+2,DIST_MAX,CENTERS,FACE_AREAS,VOLUMES,BOUNDS,MS_TYPE)
CALL CPU_TIME(TCPU2)

WRITE(99,'(A21,E20.12)') 'MESH GENERATION TIME,',TCPU2-TCPU1
WRITE(99,'(A34,E20.12)') 'MAXIMUM DISTANCE BETWEEN ELEMENTS,',DIST_MAX

!!!INITIAL CONDITION
ALLOCATE(RHO(NX+2,NY+2,NZ+2),VX(NX+2,NY+2,NZ+2),VY(NX+2,NY+2,NZ+2),VZ(NX+2,NY+2,NZ+2),ENE(NX+2,NY+2,NZ+2),PRE(NX+2,NY+2,NZ+2))

CALL CPU_TIME(TCPU1)
CALL COND_INITIAL_CUBE(NX+2,NY+2,NZ+2,CENTERS,CI_TYPE,RHO,VX,VY,VZ,ENE,PRE,BOUNDS)
CALL CPU_TIME(TCPU2)

WRITE(99,'(A23,E20.12)') 'INITIAL CONDITION TIME,',TCPU2-TCPU1

!!!SAVE 2D SLICE
CALL GNUPLOT_CUBE(NX+2,NY+2,NZ+2,0,0,CENTERS,RHO,PRE,VX,VY,VZ,BOUNDS)

!!!SAVE 3D FULL
!CALL GNUPLOT_CUBE(NX+2,NY+2,NZ+2,0,1,CENTERS,RHO,PRE,VX,VY,VZ,BOUNDS)


!!!LE3D
CALL CPU_TIME(TCPU1)
IF (DISC_TYPE==0) THEN !FULLY-DISCRETE
CALL LE3D_CUBE_FULLY(T0,TF,CFL_BASE,NX+2,NY+2,NZ+2,BORDER_TYPE,DIST_MAX,FACE_AREAS,VOLUMES,&
FLUX_TYPE,FLUX_DATA,ANIMA_FRAME,CENTERS,RHO,VX,VY,VZ,ENE,PRE,BOUNDS)
ELSE				   !SEMI-DISCRETE
CALL LE3D_CUBE_SEMI(T0,TF,CFL_BASE,NX+2,NY+2,NZ+2,BORDER_TYPE,DIST_MAX,FACE_AREAS,VOLUMES,&
FLUX_TYPE,FLUX_DATA,ANIMA_FRAME,CENTERS,RHO,VX,VY,VZ,ENE,PRE,BOUNDS)
END IF
CALL CPU_TIME(TCPU2)
WRITE(99,'(A10,E20.12)') 'LE3D TIME,',TCPU2-TCPU1


! !!!SAVE 3D FULL
! ! CALL GNUPLOT_CUBE(MPI_P,MPI_ID,NX_LOCAL,NY_LOCAL,NZ_LOCAL,MPI_NX,MPI_NY,MPI_NZ,1,BLOCK_ADRESS,1,CENTERS,&
! ! RHO,PRE,VX,VY,VZ,BOUNDS)


!!!WRITE OUTPUT FILE
OPEN(2,FILE='OUTPUT/FINAL/RHO.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) RHO
WRITE(2) I,RHO,I
CLOSE(2)

OPEN(2,FILE='OUTPUT/FINAL/VX.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) VX
WRITE(2) I,VX,I
CLOSE(2)

OPEN(2,FILE='OUTPUT/FINAL/VY.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) VY
WRITE(2) I,VY,I
CLOSE(2)

OPEN(2,FILE='OUTPUT/FINAL/VZ.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) VZ
WRITE(2) I,VZ,I
CLOSE(2)

OPEN(2,FILE='OUTPUT/FINAL/PRE_ID.DAT',FORM='UNFORMATTED',ACCESS='STREAM')
INQUIRE(IOLENGTH=I) PRE
WRITE(2) I,PRE,I
CLOSE(2)

MANIPULA = SYSTEM('rm -r OUTPUT/BACKUP')

END SELECT


!!!FINISH TIME COUNTING AND CLOSE LOG FILE (MAIN PROCESS ONLY)
CALL CPU_TIME(TCPU_FINISH)
WRITE(99,'(A11,E20.12)') 'TOTAL TIME,',TCPU_FINISH-TCPU_START
CLOSE(99)
END PROGRAM PRINCIPAL