GF     = pgf90
FFLAGS = -cuda -gpu=cc61
LFLAGS = -o

OBJETOS_3 = MAIN.F90 MESH_CUBE.F90 INITIAL_CONDITION_CUBE.F90 INITIAL_CONDITION_CUBE_CUDA.F90 GNUPLOT_CUBE.F90 LE3D_CUBE_FULLY.F90\
	    LE3D_SCHEME_CUDA.F90 LE3D_CUBE_SEMI.F90
	    
PROG_3: $(OBJETOS_3)
	$(GF) $(LFLAGS) le3dEEcuda $(OBJETOS_3) $(FFLAGS)
