!CUBE MESH GENERATOR(PEDRO GODOI 2025)
SUBROUTINE MESH_CUBE(X0,XF,Y0,YF,Z0,ZF,NX,NY,NZ,DIST_MAX,CENTERS,AREAS,VOLUMES,BOUNDS,MS_TYPE)


USE ISO_C_BINDING

IMPLICIT NONE
!INPUT
REAL(KIND=C_DOUBLE),INTENT(IN)  :: X0,XF,Y0,YF,Z0,ZF
INTEGER(KIND=C_INT),INTENT(IN)	:: NX,NY,NZ,MS_TYPE

!OUTPUT
REAL(KIND=C_DOUBLE),INTENT(OUT)                         :: DIST_MAX,VOLUMES
REAL(KIND=C_DOUBLE),DIMENSION(6),INTENT(OUT)            :: AREAS
REAL(KIND=C_DOUBLE),DIMENSION(NX,NY,NZ,3),INTENT(OUT)	:: CENTERS
INTEGER(KIND=C_INT),DIMENSION(NX,NY,NZ),INTENT(OUT)	    :: BOUNDS

!LOCAL VARIABLES
REAL(KIND=C_DOUBLE)        :: DX,DY,DZ,X_VAL,Y_VAL,Z_VAL
INTEGER(KIND=C_INT)        :: I,J,K,EL,MPI_ERR

!!!DELTAS
DX=(XF-X0)/(NX-2)
!DY=(YF-Y0)/NY
DZ=(ZF-Z0)/(NZ-2)
DY=DZ				!Y-AXIS HAVE THE SAME PARTITION SIZE AS X-AXIS BUT ONLY NY_LOCAL ELEMENTS

!!!AUXILIARY VALUES
X_VAL=X0-DX/2.0d0	!FIRST CUBE CENTER
!Y_VAL=Y0-DY/2.0d0
Z_VAL=Z0-DZ/2.0d0
Y_VAL=X_VAL

!!!MAX DISTANCE BETWEEN TWO ELEMENTS
DIST_MAX=MAXVAL((/DX,DY,DZ/))

!!!AREAS
AREAS=(/DY*DZ,DY*DZ,DX*DZ,DX*DZ,DX*DY,DX*DY/)

!!!VOLUMES
VOLUMES=DX*DY*DZ

!!!START BOUNDS
BOUNDS=0

!!!MESH GENERATOR
SELECT CASE(MS_TYPE)
CASE(0) !EULER
DO K=1,NZ
    DO J=1,NY
        DO I=1,NX
            CENTERS(I,J,K,:)=(/X_VAL+(I-1)*DX,Y_VAL+(J-1)*DY,Z_VAL+(K-1)*DZ/)      		   !WRITE COORDINATE
        END DO !I
    END DO !J
END DO !K

END SELECT

!PRINT*,NORM2(CENTERS)
END SUBROUTINE